### ISSUE TITLE
`make devnet-up` no longer works for latest develop branch

### ISSUE THREAD

**Issue by zhiqiangxu** [ethereum-optimism/optimism#10746]
This is what I got when running:

```bash
------
 > [l2 2/3] RUN apk add --no-cache jq:
0.202 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
0.818 281BBFBBC07F0000:error:0A000126:SSL routines::unexpected eof while reading:ssl/record/rec_layer_s3.c:687:
0.820 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
0.820 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: Permission denied
0.842 281BBFBBC07F0000:error:0A000126:SSL routines::unexpected eof while reading:ssl/record/rec_layer_s3.c:687:
0.844 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: Permission denied
0.844 ERROR: unable to select packages:
0.844   jq (no such package):
0.844     required by: world[jq]
------
failed to solve: process "/bin/sh -c apk add --no-cache jq" did not complete successfully: exit code: 1
Traceback (most recent call last):
  File "/Users/alanxu/Desktop/github/optimism/./bedrock-devnet/main.py", line 9, in <module>
    main()
  File "/Users/alanxu/Desktop/github/optimism/./bedrock-devnet/main.py", line 5, in main
    devnet.main()
  File "/Users/alanxu/Desktop/github/optimism/bedrock-devnet/devnet/__init__.py", line 118, in main
    run_command(['docker', 'compose', 'build', '--progress', 'plain',
  File "/Users/alanxu/Desktop/github/optimism/bedrock-devnet/devnet/__init__.py", line 385, in run_command
    return subprocess.run(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'compose', 'build', '--progress', 'plain', '--build-arg', 'GIT_COMMIT=93a24327cbe64d67484b6c43715777fb64c752c7', '--build-arg', 'GIT_DATE=1717548032']' returned non-zero exit status 17.
make: *** [devnet-up] Error 1
```

**Comment by tynes** [comment]
It has been building in CI. I would be very surprised if `jq` was removed from `apk`

**Comment by zhiqiangxu** [comment]
> It has been building in CI. I would be very surprised if `jq` was removed from `apk`

That's weird, in theory docker should build everywhere, now it always reports the above error on my macbook.

**Comment by tynes** [comment]
This is likely a transient issue, closing this as it works in CI
