### ISSUE TITLE
eth2-testnet-genesis: not found on v1.9.0

### ISSUE THREAD

**Issue by imnotanoob** [ethereum-optimism/optimism#11425]
If I try to run `make devnet-up` on v1.9.0 - i get this error.

```
eth2-testnet-genesis path: 
l1-generate-beacon-genesis.sh: 7: eth2-testnet-genesis: not found
Traceback (most recent call last):
  File "/optimism/./bedrock-devnet/main.py", line 9, in <module>
    main()
  File "/optimism/./bedrock-devnet/main.py", line 5, in main
    devnet.main()
  File "/optimism/bedrock-devnet/devnet/__init__.py", line 118, in main
    devnet_deploy(paths)
  File "/optimism/bedrock-devnet/devnet/__init__.py", line 201, in devnet_deploy
    run_command([
  File "/optimism/bedrock-devnet/devnet/__init__.py", line 365, in run_command
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sh', 'l1-generate-beacon-genesis.sh']' returned non-zero exit status 127
```

I think there was some missing configuration.

**Comment by imnotanoob** [comment]
It looks like with the changes, need to add this to my path for it to find it

**Comment by priyanshuthapliyal55** [comment]
how did you fix this i also getting same error ?

> It looks like with the changes, need to add this to my path for it to find it
