### ISSUE TITLE
make devnet-up is broken

### ISSUE THREAD

**Issue by samlaf** [ethereum-optimism/optimism#12354]
**Bug Description**

`make devnet-up`
results in this error:
```
Traceback (most recent call last):
  File "/Users/samlaf/devel/eigenlayer/da-integrations/optimism/./bedrock-devnet/main.py", line 9, in <module>
    main()
  File "/Users/samlaf/devel/eigenlayer/da-integrations/optimism/./bedrock-devnet/main.py", line 5, in main
    devnet.main()
  File "/Users/samlaf/devel/eigenlayer/da-integrations/optimism/bedrock-devnet/devnet/__init__.py", line 120, in main
    devnet_deploy(paths)
  File "/Users/samlaf/devel/eigenlayer/da-integrations/optimism/bedrock-devnet/devnet/__init__.py", line 250, in devnet_deploy
    l2_output_oracle = addresses['L2OutputOracleProxy']
                       ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'L2OutputOracleProxy'
make: *** [devnet-up] Error 1
```

**Environment Information:**

on develop branch 

**Configurations:**

**Logs:**

**Additional context**

Think this is the culprit https://github.com/ethereum-optimism/optimism/pull/11817/files#diff-d5b1923bb59d7a16b2affecb73b46f01db70d432a231d3ef5db751c4a2e42c5bL703: seems like the saving of the output oracle to addresses.json file was removed. Guessing this is just a mistake and we need to add it back, but not sure what this new interface is supposed to do. Maybe this is intended and its __init__.py which needs to be changes to remove this reading of L2outputoracleproxy?

**Comment by tynes** [comment]
We should add a check in the python script so that the `L2OutputOracle{Proxy}` are optional
