### ISSUE TITLE
interop: `panic` Condition When Supervisor is Uninitialized

### ISSUE THREAD

**Issue by axelKingsley** [ethereum-optimism/optimism#12905]
# Summary
When in need of sync, the Supervisor hits `panic` crash conditions if `op-node` or `op-geth` resources are up.

# `panic`
The basic `panic` is well known: `panic: invalid parent block 0x0000000000000000000000000000000000000000000000000000000000000000:0 to combine with BlockSeal(hash:0xb35d69e90f747e8cd6be0a6822cadd306a14fd592f7967da7769da4f63246652, number:4689, time:1731440267)`.
In this, message, we see that we attempt to combine Block Number 4689 with Parent Block Number 0. Of course, that would be the wrong thing to do, so this panic indicates real error.

The full trace for the faulting goroutine:
```
goroutine 105 [running]:
github.com/ethereum-optimism/optimism/op-supervisor/supervisor/types.BlockSeal.MustWithParent(...)
        /app/op-supervisor/supervisor/types/types.go:254
github.com/ethereum-optimism/optimism/op-supervisor/supervisor/backend/db.(*ChainsDB).CandidateCrossSafe(0x400069f320, {0xdbc68, 0x0, 0x0, 0x0})
        /app/op-supervisor/supervisor/backend/db/query.go:253 +0x11cc
github.com/ethereum-optimism/optimism/op-supervisor/supervisor/backend/cross.scopedCrossSafeUpdate({0xf5dcb8, 0x40004f8f70}, {0xdbc68, 0x0, 0x0, 0x0}, {0xf5c940, 0x400069f320})
        /app/op-supervisor/supervisor/backend/cross/safe_update.go:73 +0x6c
github.com/ethereum-optimism/optimism/op-supervisor/supervisor/backend/cross.CrossSafeUpdate({0xbb044c?, 0x39?}, {0xf5dcb8, 0x40004f8f70}, {0xdbc68, 0x0, 0x0, 0x0}, {0xf5c940, 0x400069f320})
        /app/op-supervisor/supervisor/backend/cross/safe_update.go:33 +0x80
github.com/ethereum-optimism/optimism/op-supervisor/supervisor/backend/cross.NewCrossSafeWorker.func1({0xf55148?, 0x40000938b0?})
        /app/op-supervisor/supervisor/backend/cross/safe_update.go:106 +0x44
github.com/ethereum-optimism/optimism/op-supervisor/supervisor/backend/cross.(*Worker).worker(0x4000093900)
        /app/op-supervisor/supervisor/backend/cross/worker.go:68 +0x94
created by github.com/ethereum-optimism/optimism/op-supervisor/supervisor/backend/cross.(*Worker).StartBackground in goroutine 1
        /app/op-supervisor/supervisor/backend/cross/worker.go:51 +0x70
panic: invalid parent block 0x0000000000000000000000000000000000000000000000000000000000000000:0 to combine with BlockSeal(hash:0xb35d69e90f747e8cd6be0a6822cadd306a14fd592f7967da7769da4f63246652, number:4689, time:1731440267)
```

In this, we can see that the fault is happening during `scopedCrossSafeUpdate`

# Root Cause and Conceptual Fix
This issue happens when a Supervisor is syncing from scratch while the network is already running. It appears that when the `fromda` database is empty, callers (I think `op-geth`) ask for updates to Cross-Safety. This in turn makes its way all the way to `scopedCrossSafeUpdate`.

The supervisor should be able to detect and deny requests to the database which are obviously beyond the sync'd scope. This particular codepath is triggering because it's being identified as the "first" block in the database. It is obviously incorrect, but we should stop the call from even getting this far if the database is empty.

# Reproduction Steps
- Launch `local-devnet` (guides are lacking @axelKingsley can make one)
- Allow the network to progress for a few moments
- `sh` into the Supervisor container and run `rm -rf /db/* && killall op-supervisor` to destroy the database and immediately stop the supervisor.
- Relaunch the supervisor, and observe the logs
- After a few moments of runtime, the `panic` should occur.

**Comment by protolambda** [comment]
This is being addressed by the Anchor-point change in the dataflow refactor PR.

**Comment by ghost** [comment]
This was resolved in https://github.com/ethereum-optimism/optimism/pull/13481
