### ISSUE TITLE
op-conductor: SEGFAULT when peer is killed during leader election

### ISSUE THREAD

**Issue by dpulitano** [ethereum-optimism/optimism#13363]
**Bug Description**
It appears invalid data is written to raft logs in op-conductor when an op-conductor instance is going through a leader re-election and its only peer is killed -- leading to SEGFAULTs

**Steps to Reproduce**
I am using op-conductors locally with Docker Arm64 v0.2.0. The Raft log data is persisted on a unique Docker volume by each op-conductor instance.

Started 3 sets of op-node and op-conductor with conductor.paused = false.
After one conductor (op-conductor1 / dan-p-local-raft-server-id-1 / 127.0.0.1:18547) had bootstrapped itself, I added another conductor instance as a voting member with:
```
cast rpc conductor_addServerAsVoter "dan-p-local-raft-server-id-0" "op-conductor:50050" 0 --rpc-url http://127.0.0.1:18547
```

This led to the 2 conductor instances quickly gaining and then giving up leadership because conductor considered their respective sequencers unhealthy. After stopping the op-conductor instance running on `dan-p-local-raft-server-id-0`, immediately op-conductor1 / dan-p-local-raft-server-id-1 (running at localhost:18547) crashes with the following:
```
2024-12-11 15:31:11 t=2024-12-11T20:31:11+0000 lvl=error msg="server (follower) is not healthy" server=dan-p-local-raft-server-id-1
2024-12-11 15:31:12 t=2024-12-11T20:31:12+0000 lvl=error msg="unsafe head is falling behind the unsafe interval" now=1733949072 unsafe_head_num=0 unsafe_head_time=1733947980 unsafe_interval=5 cur_unsafe_time_diff=1092
2024-12-11 15:31:12 t=2024-12-11T20:31:12+0000 lvl=error msg="Sequencer is unhealthy" server=dan-p-local-raft-server-id-1 err="sequencer is not healthy"
2024-12-11 15:31:12 t=2024-12-11T20:31:12+0000 lvl=error msg="server (follower) is not healthy" server=dan-p-local-raft-server-id-1
2024-12-11 15:31:13 t=2024-12-11T20:31:13+0000 lvl=error msg="unsafe head is falling behind the unsafe interval" now=1733949073 unsafe_head_num=0 unsafe_head_time=1733947980 unsafe_interval=5 cur_unsafe_time_diff=1093
2024-12-11 15:31:13 t=2024-12-11T20:31:13+0000 lvl=error msg="Sequencer is unhealthy" server=dan-p-local-raft-server-id-1 err="sequencer is not healthy"
2024-12-11 15:31:13 t=2024-12-11T20:31:13+0000 lvl=error msg="server (follower) is not healthy" server=dan-p-local-raft-server-id-1
2024-12-11 15:31:13 2024-12-11T20:31:13.802Z [INFO]  raft: starting snapshot up to: index=64402
2024-12-11 15:31:13 2024-12-11T20:31:13.802Z [INFO]  snapshot: creating new snapshot: path=/conductor/raft/dan-p-local-raft-server-id-1/snapshots/32165-64402-1733949073802.tmp
2024-12-11 15:31:13 panic: runtime error: invalid memory address or nil pointer dereference
2024-12-11 15:31:13 [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8172b0]
2024-12-11 15:31:13 
2024-12-11 15:31:13 goroutine 64 [running]:
2024-12-11 15:31:13 github.com/ethereum-optimism/optimism/op-service/eth.(*ExecutionPayloadEnvelope).MarshalSSZ(0x2269680?, {0xffff390912f8?, 0x40004f40f0?})
2024-12-11 15:31:13     /app/op-service/eth/ssz.go:464 +0x20
2024-12-11 15:31:13 github.com/ethereum-optimism/optimism/op-conductor/consensus.(*snapshot).Persist(0x4000b66ab0, {0x1786560, 0x40004f40f0})
2024-12-11 15:31:13     /app/op-conductor/consensus/raft_fsm.go:98 +0x50
2024-12-11 15:31:13 github.com/hashicorp/raft.(*Raft).takeSnapshot(0x40003bd8c8)
2024-12-11 15:31:13     /go/pkg/mod/github.com/hashicorp/raft@v1.7.1/snapshot.go:190 +0x690
2024-12-11 15:31:13 github.com/hashicorp/raft.(*Raft).runSnapshots(0x40003bd8c8)
2024-12-11 15:31:13     /go/pkg/mod/github.com/hashicorp/raft@v1.7.1/snapshot.go:82 +0x300
2024-12-11 15:31:13 github.com/hashicorp/raft.(*raftState).goFunc.func1()
2024-12-11 15:31:13     /go/pkg/mod/github.com/hashicorp/raft@v1.7.1/state.go:149 +0x60
2024-12-11 15:31:13 created by github.com/hashicorp/raft.(*raftState).goFunc in goroutine 1
2024-12-11 15:31:13     /go/pkg/mod/github.com/hashicorp/raft@v1.7.1/state.go:147 +0x84
```

It appears invalid raft data was written to disk because after restarting all services in the cluster (this time with conductor.paused on all instances), the same SEGFAULT is returned.

I am able to reproduce this consistently by following the above steps.

**Expected behavior**
Raft data that is persisted to disk should never result in a SEGFAULT

**Environment Information:**

 - Operating System: MacOS Sonoma 14.7.1 (23H222)
 - Package Version (or commit hash): op-conductor:v0.0.2 running via Docker ARM64 image / op-node:v1.9.5 running via Docker ARM64 image

**Configurations:**
3 op-node instances with similar settings to:
```
  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:${OP_NODE_IMAGE_TAG}
    platform: linux/arm64
    entrypoint: ["op-node"]
    environment:
      - OP_NODE_L1_BEACON_IGNORE=true
      - OP_NODE_CONDUCTOR_ENABLED=true
      - OP_NODE_CONDUCTOR_RPC=http://op-conductor:8547
    command: >
      --l2=http://op-geth:9551
      --l2.jwt-secret=/jwt.txt
      --sequencer.enabled=true
      --sequencer.l1-confs=5
      --verifier.l1-confs=4
      --rollup.config=/rollup.json
      --rpc.addr=0.0.0.0
      --rpc.port=9545
      --rpc.enable-admin
      --p2p.sequencer.key=${GS_SEQUENCER_PRIVATE_KEY}
      --p2p.static="{op-node1-peer-string},{op-node2-peer-string}"
      --p2p.listen.udp=9222
      --p2p.priv.path=/op-node/opnode_p2p_priv.txt
      --p2p.no-discovery=true
      --l1=${L1_RPC_URL}
      --l1.rpckind=standard
      --l1.trustrpc
      --override.ecotone=0
      --override.fjord=0
      --override.granite=0
      --safedb.path=/op-node/safedb-data
    ports:
      - "9545:9545"
    volumes:
      - ${JWT_PATH}:/jwt.txt
      - ${ROLLUP_PATH}:/rollup.json
      - op-node:/op-node
    depends_on:
      - op-geth
    networks:
      front-tier:
        ipv4_address: 172.16.238.201
```

3 op-conductor instances with similar settings to:
```
  op-conductor:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-conductor:v0.2.0
    platform: linux/arm64
    entrypoint: ["op-conductor"]
    environment:
      OP_CONDUCTOR_ROLLUP_CONFIG: /rollup.json
      OP_CONDUCTOR_CONSENSUS_ADDR: 'op-conductor'
      OP_CONDUCTOR_CONSENSUS_PORT: '50050'
      OP_CONDUCTOR_EXECUTION_RPC: 'http://op-geth:8545'
      OP_CONDUCTOR_HEALTHCHECK_INTERVAL: '1'
      OP_CONDUCTOR_HEALTHCHECK_MIN_PEER_COUNT: '1'
      OP_CONDUCTOR_HEALTHCHECK_UNSAFE_INTERVAL: '5' # recommend a 2-3x multiple of your network block time to account for temporary performance issues
      OP_CONDUCTOR_LOG_FORMAT: logfmt
      OP_CONDUCTOR_LOG_LEVEL: info
      OP_CONDUCTOR_METRICS_ADDR: 0.0.0.0
      OP_CONDUCTOR_METRICS_ENABLED: 'true'
      OP_CONDUCTOR_METRICS_PORT: '7300'
      OP_CONDUCTOR_NODE_RPC: 'http://op-node:9545'
      OP_CONDUCTOR_RAFT_SERVER_ID: 'dan-p-local-raft-server-id-0'
      OP_CONDUCTOR_RAFT_STORAGE_DIR: /conductor/raft
      OP_CONDUCTOR_RPC_ADDR: 0.0.0.0
      OP_CONDUCTOR_RPC_ENABLE_ADMIN: 'true'
      OP_CONDUCTOR_RPC_ENABLE_PROXY: 'true'
      OP_CONDUCTOR_RPC_PORT: '8547'
    depends_on:
      - op-geth
      - op-node
    ports:
      - "50049:50050"
      - "8547:8547"
    volumes:
      - ${ROLLUP_PATH}:/rollup.json
      - conductor-raft-data:/conductor/raft
    networks:
      front-tier:
        ipv4_address: 172.16.238.151
```

- instance `op-conductor1` also had `OP_CONDUCTOR_RAFT_BOOTSTRAP: true` added.

All services use unique ipv4 urls

**Logs:**

**Additional context**
Included above

---

⚠️ **Notice:** Issues that do not include the following sections will be subject to closure:
- Bug Description
- Steps to Reproduce
- Environment Information

Please ensure all required sections are filled out accurately to expedite the debugging process and improve issue resolution efficiency.

**Comment by tynes** [comment]
Ideally there is a way to run `op-conductor` in [kurtosis](https://github.com/ethpandaops/optimism-package) and then we can more easily create reproducible ways to spin up the system on any developer's machine with a single command. Just flagging this for @mslipper to think about longer term

**Comment by 0x00101010** [comment]
Hey @dpulitano, actually the SEGFAULT looks like that the payload is not actually committed to raft / conductor, thus failed to be written to disk (with nil data). suggest you to check

1. if conductors are actually formed as a cluster, [api to call](https://github.com/ethereum-optimism/optimism/blob/develop/op-conductor/rpc/backend.go#L139)
2. and check on the logs of commit unsafe payload, see if there's any errors there

Also +1 to integrate it into kurtosis

**Comment by dpulitano** [comment]
+1, agree having a script to spin up a conductor cluster would be great. Eventually I figured it out with some playing around but it took some effort.

Yeah my guess too is that truncated or nil data gets committed the raft logs or snapshot file.


Repeated the same test and after making the RPC call to add the second peer, querying either server shows it is a cluster:
```
% cast rpc conductor_clusterMembership -r http://localhost:18547 | jq
{
  "servers": [
    {
      "id": "local-raft-server-id-1",
      "addr": "op-conductor1:50050",
      "suffrage": 0
    },
    {
      "id": "local-raft-server-id-0",
      "addr": "op-conductor:50050",
      "suffrage": 0
    }
  ],
  "version": 0
}
% cast rpc conductor_clusterMembership -r http://localhost:8547 | jq 
{
  "servers": [
    {
      "id": "local-raft-server-id-1",
      "addr": "op-conductor1:50050",
      "suffrage": 0
    },
    {
      "id": "local-raft-server-id-0",
      "addr": "op-conductor:50050",
      "suffrage": 0
    }
  ],
  "version": 0
}
```

This time when I tested, I actually got the error to appear without manually killing either op-conductor instance.
I now think it's because the raft library decided to take a snapshot, since I don't see any mention of this log anywhere except right before the fault:
```
2024-12-19 10:24:31 2024-12-19T15:24:31.352Z [INFO]  raft: starting snapshot up to: index=113348
```

Looking at the raft library code, I see that the server decides to take a snapshot if the amount of "outstanding logs" exceeds the `SnapshotThreshold` (the default is 8192)

This led me to think that since I previously cleared the raft data on all servers before this test, maybe this invalid nil data was written because no unsafe logs were able to be committed.

So I ran an additional test by first:
1. Clearing the conductor raft disks
2. Bootstrapped a new single node cluster
3. Made the single node cluster leader the active sequencer and confirmed it committed unsafe blocks

before stopping all conductor and op-node instances w/o clearing any disks.

Now if I restart all conductors and op-nodes (with conductor.paused = false) and then add another voter to the cluster (before any op-nodes have finished starting up), I see that a leader was elected and active sequencer started successfully. So I'm pretty sure that this stems from there not yet being any unsafe head raft data committed.

I will have to dig into this but I'm wondering if there is a way of bootstrapping the raft data so that:
1. This SEGFAULT bug doesn't occur, and
2. There's no need to pause the conductors while we wait for the initial unsafe head information to get committed (maybe some special "None" value can be persisted which can be safely interpretted by all readers of the logs) -- therefore avoiding no leader staying elected.

**Comment by 0x00101010** [comment]
Can you share in detail steps how you setup your cluster?

Some things to note:
1. if unsafe head commit is configured properly, 8192 logs should be more than enough
2. please be careful to restart conductor in unpaused state, especially if you started it in bootstrap mode (make sure during restart, it's not bootstrap mode)

**Comment by 0xVasconcelos** [comment]
+1 


Problem is still present in the current version. 
We have deployed conductor to migrate from single->HA and while we wait to all nodes to get in sync we keep the sequencers paused, and during this period it tries to snapshot even with conductors pauses causing this issue.
