### ISSUE TITLE
Flickering test (race condition with eth_call and rollup_getInfo)

### ISSUE THREAD

**Issue by snario** [ethereum-optimism/optimism#1614]
See [here](https://github.com/ethereum-optimism/optimism/runs/3957327086?check_suite_focus=true) for an example.

```
  1) OVM Context: Layer 2 EVM Context
       should return same timestamp and blocknumbers between `eth_call` and `rollup_getInfo`:

      AssertionError: expected 193 to deeply equal 190
      + expected - actual

      -193
      +190
      
      at Context.<anonymous> (test/ovmcontext.spec.ts:162:49)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by smartcontracts** [comment]
We deleted this test
