### ISSUE TITLE
Flaky integration test (timeout running stress tests)

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#1686]
**Describe the bug**
I saw this timeout in GH actions, figured it should be logged so someone can take a look later: https://github.com/ethereum-optimism/optimism/runs/4096831701?check_suite_focus=true#step:11:170

```

  1) stress tests
       C-C-C-Combo breakers
         3 L2 transactions, L1 => L2 transactions, L2 => L1 transactions (all parallel):
     Error: timeout (requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf9012706808301638094420000000000000000000000000000000000000780b8c43dbb202b000000000000000000000000dbc43ba45381e02825b14322cddd15ec4b3164e6000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000007a1200000000000000000000000000000000000000000000000000000000000000002458825b1042424242424242424242424242424242424242424242424242424242424242420000000000000000000000000000000000000000000000000000000082036ba01408604b253d6ba09c2a5620acb5f47bc315039f96c9e49fb0380a406802ec9fa00e83e53f2710feb68ac07af0e28e7819d0fe93fe433fafe160fb3881c3e862d0\"],\"id\":3117,\"jsonrpc\":\"2.0\"}", requestMethod="POST", timeout=120000, url="http://l2geth:8545", code=TIMEOUT, version=web/5.4.0)
      at Logger.makeError (/opt/optimism/node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
      at Timeout._onTimeout (/opt/optimism/node_modules/@ethersproject/web/src.ts/index.ts:180:35)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

**Comment by cfromknecht** [comment]
Closed by #1785. This flake now manifests itself as the error in #1891
