### ISSUE TITLE
Flaky integration test ("Cannot commit transaction in miner")

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#1891]
**Describe the bug**
Seeing a flaky integration test. [Here's the CI run](https://github.com/ethereum-optimism/optimism/runs/4449858570?check_suite_focus=true#step:8:210). Occurs in the stress tests, same area where we saw the timeout in #1686.

```
  1) stress tests
       C-C-C-Combo breakers
         3 L2 transactions, L1 => L2 transactions, L2 => L1 transactions (all parallel):
     Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":3847,\"error\":{\"code\":-32000,\"message\":\"Cannot commit transaction in miner\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf88606018301a6fb94aa292e8611adf267e563f334ee42320ac96d046380a49faa1de3424242424242424242424242424242424242424242424242424242424242424282036ca0f0cebf9bf813f6c02244c24558165b94a8d616ef81c2a8d0738db70192ceaf62a02a812f19c39e088e6a611de000943c5cda4fbdcb712c95c35d12caded9cf071a\"],\"id\":3847,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://l2geth:8545", code=SERVER_ERROR, version=web/5.4.0)
      at Logger.makeError (/optimism/node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
      at Logger.throwError (/optimism/node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
      at /optimism/node_modules/@ethersproject/web/src.ts/index.ts:284:28
      at step (/optimism/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/optimism/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/optimism/node_modules/@ethersproject/web/lib/index.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Expected behavior**
Test should pass or fail consistently.

**Comment by cfromknecht** [comment]
@smartcontracts there is a WIP PR address this, see #1816
