### ISSUE TITLE
relayer: unhandled exception

### ISSUE THREAD

**Issue by palango** [ethereum-optimism/optimism#2211]
**Describe the bug**
When running the relayer service it crashes when relaying a message.

```
{"level":30,"time":1644857979284,"msg":"checking L2 block 30"}
{"level":50,"time":1644857979440,"extra":{"message":"TypeError: Cannot read properties of null (reading 'args')","stack":"TypeError: Cannot read properties of null (reading 'args')\n    at isEventLo (/opt/optimism/packages/sdk/src/cross-chain-messenger.ts:641:39)\n    at CrossChainMessenger.getStateBatchAppendedEventByTransactionIndex (/opt/optimism/packages/sdk/src/cross-chain-messenger.ts:657:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async CrossChainMessenger.getStateRootBatchByTransactionIndex (/opt/optimism/packages/sdk/src/cross-chain-messenger.ts:690:7)\n    at async CrossChainMessenger.getMessageStateRoot (/opt/optimism/packages/sdk/src/cross-chain-messenger.ts:584:28)\n    at async CrossChainMessenger.getMessageStatus (/opt/optimism/packages/sdk/src/cross-chain-messenger.ts:358:27)\n    at async MessageRelayerService._start (/opt/optimism/packages/message-relayer/src/service.ts:141:28)\n    at async MessageRelayerService.start (/opt/optimism/packages/common-ts/src/base-service.ts:69:5)\n    at async main (/opt/optimism/packages/message-relayer/bin/run.ts:106:3)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1644857979943,"msg":"checking L2 block 30"}
```

Formatted:
```
Cannot read properties of null (reading 'args')
    at isEventLo (/opt/optimism/packages/sdk/src/cross-chain-messenger.ts:641:39)
    at CrossChainMessenger.getStateBatchAppendedEventByTransactionIndex (/opt/optimism/packages/sdk/src/cross-chain-messenger.ts:657:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CrossChainMessenger.getStateRootBatchByTransactionIndex (/opt/optimism/packages/sdk/src/cross-chain-messenger.ts:690:7)
    at async CrossChainMessenger.getMessageStateRoot (/opt/optimism/packages/sdk/src/cross-chain-messenger.ts:584:28)
    at async CrossChainMessenger.getMessageStatus (/opt/optimism/packages/sdk/src/cross-chain-messenger.ts:358:27)
    at async MessageRelayerService._start (/opt/optimism/packages/message-relayer/src/service.ts:141:28)
    at async MessageRelayerService.start (/opt/optimism/packages/common-ts/src/base-service.ts:69:5)
    at async main (/opt/optimism/packages/message-relayer/bin/run.ts:106:3)
```

**To Reproduce**
1. Go to `/ops'
2. Run the relayer: `docker-compose -f docker-compose.yml -f docker-compose-nobuild.yml up --scale relayer=1  -d`
3. Send a L2 -> L1 message on the rollup
4. Check relayer logs for error

**Expected behavior**
The message should be relayed

**Additional context**
This seems to have been introduced in https://github.com/ethereum-optimism/optimism/pull/2189 @smartcontracts

**Comment by smartcontracts** [comment]
Will look into this today, thanks for making this issue!

**Comment by smartcontracts** [comment]
#2214 should fix this
