### ISSUE TITLE
Building Optimistic Ethereum locally fails

### ISSUE THREAD

**Issue by chrismin** [ethereum-optimism/optimism#2429]
**Describe the bug**
Building Optimistic Ethereum locally fails. Building via Docker in the `ops/` directory fails during `RUN yarn install --frozen-lockfile && yarn cache clean`. I am running into the issue at commit `71240b1d9db330232361f2bab7669b95874ea650`, but I can build successfully at commit  `0ac233e73040b372464a9f59a325217254fe8e15`, so I imagine the issue was introduced somewhere in between.

**To Reproduce**
1. Clone repo
2. `yarn build` in root
3. `cd ops`
4. `make build`
6. See error:
``` => ERROR [ethereumoptimism/replica-healthcheck:latest base 13/16] RUN yarn install --frozen-lock  63.2s
------
 > [ethereumoptimism/replica-healthcheck:latest base 13/16] RUN yarn install --frozen-lockfile && yarn cache clean:
#36 0.686 yarn install v1.22.18
#36 0.896 [1/4] Resolving packages...
#36 2.462 [2/4] Fetching packages...
#36 40.50 [3/4] Linking dependencies...
#36 40.50 warning " > @eth-optimism/contracts@0.5.20" has unmet peer dependency "ethers@^5".
#36 40.50 warning " > @eth-optimism/sdk@1.0.4" has unmet peer dependency "ethers@^5".
#36 57.15 [4/4] Building fresh packages...
#36 59.26 warning Error running install script for optional dependency: "/opt/optimism/node_modules/node-hid: Command failed.
#36 59.26 Exit code: 1
#36 59.26 Command: prebuild-install || node-gyp rebuild
#36 59.26 Arguments:
#36 59.26 Directory: /opt/optimism/node_modules/node-hid
#36 59.26 Output:
#36 59.26 prebuild-install WARN install No prebuilt binaries found (target=16.14.2 runtime=node arch=arm64 libc=musl platform=linux)
#36 59.26 gyp info it worked if it ends with ok
#36 59.26 gyp info using node-gyp@7.1.2
#36 59.26 gyp info using node@16.14.2 | linux | arm64
#36 59.26 gyp info find Python using Python version 3.9.5 found at \"/usr/bin/python3\"
#36 59.26 gyp http GET https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
#36 59.26 gyp http 200 https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
#36 59.26 gyp http GET https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
#36 59.26 gyp http 200 https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
#36 59.26 (node:82) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
#36 59.26 (Use `node --trace-deprecation ...` to show where the warning was created)
#36 59.26 gyp info spawn /usr/bin/python3
#36 59.26 gyp info spawn args [
#36 59.26 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
#36 59.26 gyp info spawn args   'binding.gyp',
#36 59.26 gyp info spawn args   '-f',
#36 59.26 gyp info spawn args   'make',
#36 59.26 gyp info spawn args   '-I',
#36 59.26 gyp info spawn args   '/opt/optimism/node_modules/node-hid/build/config.gypi',
#36 59.26 gyp info spawn args   '-I',
#36 59.26 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
#36 59.26 gyp info spawn args   '-I',
#36 59.26 gyp info spawn args   '/root/.cache/node-gyp/16.14.2/include/node/common.gypi',
#36 59.26 gyp info spawn args   '-Dlibrary=shared_library',
#36 59.26 gyp info spawn args   '-Dvisibility=default',
#36 59.26 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.14.2',
#36 59.26 gyp info spawn args   '-Dnode_gyp_dir=/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp',
#36 59.26 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
#36 59.26 gyp info spawn args   '-Dmodule_root_dir=/opt/optimism/node_modules/node-hid',
#36 59.26 gyp info spawn args   '-Dnode_engine=v8',
#36 59.26 gyp info spawn args   '--depth=.',
#36 59.26 gyp info spawn args   '--no-parallel',
#36 59.26 gyp info spawn args   '--generator-output',
#36 59.26 gyp info spawn args   'build',
#36 59.26 gyp info spawn args   '-Goutput_dir=.'
#36 59.26 gyp info spawn args ]
#36 59.26 /bin/sh: pkg-config: not found
#36 59.26 gyp: Call to 'pkg-config libusb-1.0 --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
#36 59.26 gyp ERR! configure error
#36 59.26 gyp ERR! stack Error: `gyp` failed with exit code: 1
#36 59.26 gyp ERR! stack     at ChildProcess.onCpExit (/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/configure.js:351:16)
#36 59.26 gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
#36 59.26 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
#36 59.26 gyp ERR! System Linux 5.10.104-linuxkit
#36 59.26 gyp ERR! command \"/usr/local/bin/node\" \"/opt/optimism/node_modules/.bin/node-gyp\" \"rebuild\"
#36 59.26 gyp ERR! cwd /opt/optimism/node_modules/node-hid
#36 59.26 gyp ERR! node -v v16.14.2
#36 59.26 gyp ERR! node-gyp -v v7.1.2
#36 59.26 gyp ERR! not ok"
#36 59.26 info This module is OPTIONAL, you can safely ignore this error
#36 59.27 info This module is OPTIONAL, you can safely ignore this error
#36 59.27 warning Error running install script for optional dependency: "/opt/optimism/node_modules/@ledgerhq/hw-transport-node-hid-noevents/node_modules/node-hid: Command failed.
#36 59.27 Exit code: 1
#36 59.27 Command: prebuild-install --runtime napi || node-gyp rebuild
#36 59.27 Arguments:
#36 59.27 Directory: /opt/optimism/node_modules/@ledgerhq/hw-transport-node-hid-noevents/node_modules/node-hid
#36 59.27 Output:
#36 59.27 prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=arm64 libc=musl platform=linux)
#36 59.27 gyp info it worked if it ends with ok
#36 59.27 gyp info using node-gyp@7.1.2
#36 59.27 gyp info using node@16.14.2 | linux | arm64
#36 59.27 gyp info find Python using Python version 3.9.5 found at \"/usr/bin/python3\"
#36 59.27 gyp http GET https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
#36 59.27 gyp http 200 https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
#36 59.27 gyp http GET https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
#36 59.27 gyp http 200 https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
#36 59.27 (node:72) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
#36 59.27 (Use `node --trace-deprecation ...` to show where the warning was created)
#36 59.27 gyp info spawn /usr/bin/python3
#36 59.27 gyp info spawn args [
#36 59.27 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
#36 59.27 gyp info spawn args   'binding.gyp',
#36 59.27 gyp info spawn args   '-f',
#36 59.27 gyp info spawn args   'make',
#36 59.27 gyp info spawn args   '-I',
#36 59.27 gyp info spawn args   '/opt/optimism/node_modules/@ledgerhq/hw-transport-node-hid-noevents/node_modules/node-hid/build/config.gypi',
#36 59.27 gyp info spawn args   '-I',
#36 59.27 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
#36 59.27 gyp info spawn args   '-I',
#36 59.27 gyp info spawn args   '/root/.cache/node-gyp/16.14.2/include/node/common.gypi',
#36 59.27 gyp info spawn args   '-Dlibrary=shared_library',
#36 59.27 gyp info spawn args   '-Dvisibility=default',
#36 59.27 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.14.2',
#36 59.27 gyp info spawn args   '-Dnode_gyp_dir=/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp',
#36 59.27 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
#36 59.27 gyp info spawn args   '-Dmodule_root_dir=/opt/optimism/node_modules/@ledgerhq/hw-transport-node-hid-noevents/node_modules/node-hid',
#36 59.27 gyp info spawn args   '-Dnode_engine=v8',
#36 59.27 gyp info spawn args   '--depth=.',
#36 59.27 gyp info spawn args   '--no-parallel',
#36 59.27 gyp info spawn args   '--generator-output',
#36 59.27 gyp info spawn args   'build',
#36 59.27 gyp info spawn args   '-Goutput_dir=.'
#36 59.27 gyp info spawn args ]
#36 59.27 /bin/sh: pkg-config: not found
#36 59.27 gyp: Call to 'pkg-config libusb-1.0 --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
#36 59.27 gyp ERR! configure error
#36 59.27 gyp ERR! stack Error: `gyp` failed with exit code: 1
#36 59.27 gyp ERR! stack     at ChildProcess.onCpExit (/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/configure.js:351:16)
#36 59.27 gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
#36 59.27 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
#36 59.27 gyp ERR! System Linux 5.10.104-linuxkit
#36 59.27 gyp ERR! command \"/usr/local/bin/node\" \"/opt/optimism/node_modules/.bin/node-gyp\" \"rebuild\"
#36 59.27 gyp ERR! cwd /opt/optimism/node_modules/@ledgerhq/hw-transport-node-hid-noevents/node_modules/node-hid
#36 59.27 gyp ERR! node -v v16.14.2
#36 59.27 gyp ERR! node-gyp -v v7.1.2
#36 59.27 gyp ERR! not ok"
#36 60.29 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#36 60.29 error /opt/optimism/node_modules/bufferutil: Command failed.
#36 60.29 Exit code: 1
#36 60.29 Command: node-gyp-build
#36 60.29 Arguments:
#36 60.29 Directory: /opt/optimism/node_modules/bufferutil
#36 60.29 Output:
#36 60.29 gyp info it worked if it ends with ok
#36 60.29 gyp info using node-gyp@7.1.2
#36 60.29 gyp info using node@16.14.2 | linux | arm64
#36 60.29 gyp info find Python using Python version 3.9.5 found at "/usr/bin/python3"
#36 60.29 (node:367) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
#36 60.29 (Use `node --trace-deprecation ...` to show where the warning was created)
#36 60.29 gyp info spawn /usr/bin/python3
#36 60.29 gyp info spawn args [
#36 60.29 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
#36 60.29 gyp info spawn args   'binding.gyp',
#36 60.29 gyp info spawn args   '-f',
#36 60.29 gyp info spawn args   'make',
#36 60.29 gyp info spawn args   '-I',
#36 60.29 gyp info spawn args   '/opt/optimism/node_modules/bufferutil/build/config.gypi',
#36 60.29 gyp info spawn args   '-I',
#36 60.29 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
#36 60.29 gyp info spawn args   '-I',
#36 60.29 gyp info spawn args   '/root/.cache/node-gyp/16.14.2/include/node/common.gypi',
#36 60.29 gyp info spawn args   '-Dlibrary=shared_library',
#36 60.29 gyp info spawn args   '-Dvisibility=default',
#36 60.29 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.14.2',
#36 60.29 gyp info spawn args   '-Dnode_gyp_dir=/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp',
#36 60.29 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
#36 60.29 gyp info spawn args   '-Dmodule_root_dir=/opt/optimism/node_modules/bufferutil',
#36 60.29 gyp info spawn args   '-Dnode_engine=v8',
#36 60.29 gyp info spawn args   '--depth=.',
#36 60.29 gyp info spawn args   '--no-parallel',
#36 60.29 gyp info spawn args   '--generator-output',
#36 60.29 gyp info spawn args   'build',
#36 60.29 gyp info spawn args   '-Goutput_dir=.'
#36 60.29 gyp info spawn args ]
#36 60.29 gyp info spawn make
#36 60.29 gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
#36 60.29 make: Entering directory '/opt/optimism/node_modules/bufferutil/build'
#36 60.29   CC(target) Release/obj.target/bufferutil/src/bufferutil.o
#36 60.29   SOLINK_MODULE(target) Release/obj.target/bufferutil.node
#36 60.29 make: g++: No such file or directory
#36 60.29 make: *** [bufferutil.target.mk:137: Release/obj.target/bufferutil.node] Error 127
#36 60.29 make: Leaving directory '/opt/optimism/node_modules/bufferutil/build'
#36 60.29 gyp ERR! build error
#36 60.29 gyp ERR! stack Error: `make` failed with exit code: 2
#36 60.29 gyp ERR! stack     at ChildProcess.onExit (/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/build.js:194:23)
#36 60.29 gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
#36 60.29 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
#36 60.29 gyp ERR! System Linux 5.10.104-linuxkit
#36 60.29 gyp ERR! command "/usr/local/bin/node" "/opt/optimism/node_modules/.bin/node-gyp" "rebuild"
#36 60.29 gyp ERR! cwd /opt/optimism/node_modules/bufferutil
#36 60.29 gyp ERR! node -v v16.14.2
#36 60.29 gyp ERR! node-gyp -v v7.1.2
#36 60.29 gyp ERR! not ok
#36 60.98 warning Error running install script for optional dependency: "/opt/optimism/node_modules/usb: Command failed.
#36 60.98 Exit code: 1
#36 60.98 Command: prebuild-install --runtime napi --target 4 --verbose || node-gyp rebuild
#36 60.98 Arguments:
#36 60.98 Directory: /opt/optimism/node_modules/usb
#36 60.98 Output:
#36 60.98 prebuild-install info begin Prebuild-install version 5.3.6
#36 60.98 prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/ab1e1c-usb-v1.7.1-napi-v4-linuxmusl-arm64.tar.gz
#36 60.98 prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.7.1/usb-v1.7.1-napi-v4-linuxmusl-arm64.tar.gz
#36 60.98 prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.7.1/usb-v1.7.1-napi-v4-linuxmusl-arm64.tar.gz
#36 60.98 prebuild-install WARN install No prebuilt binaries found (target=4 runtime=napi arch=arm64 libc=musl platform=linux)
#36 60.98 gyp info it worked if it ends with ok
#36 60.98 gyp info using node-gyp@7.1.2
#36 60.98 gyp info using node@16.14.2 | linux | arm64
#36 60.98 gyp info find Python using Python version 3.9.5 found at \"/usr/bin/python3\"
#36 60.98 gyp http GET https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
#36 60.98 gyp http 200 https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
#36 60.98 gyp http GET https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
#36 60.98 gyp http 200 https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
#36 60.98 (node:50) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
#36 60.98 (Use `node --trace-deprecation ...` to show where the warning was created)
#36 60.98 gyp info spawn /usr/bin/python3
#36 60.98 gyp info spawn args [
#36 60.98 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
#36 60.98 gyp info spawn args   'binding.gyp',
#36 60.98 gyp info spawn args   '-f',
#36 60.98 gyp info spawn args   'make',
#36 60.98 gyp info spawn args   '-I',
#36 60.98 gyp info spawn args   '/opt/optimism/node_modules/usb/build/config.gypi',
#36 60.98 gyp info spawn args   '-I',
#36 60.98 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
#36 60.98 gyp info spawn args   '-I',
#36 60.98 gyp info spawn args   '/root/.cache/node-gyp/16.14.2/include/node/common.gypi',
#36 60.98 gyp info spawn args   '-Dlibrary=shared_library',
#36 60.98 gyp info spawn args   '-Dvisibility=default',
#36 60.98 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.14.2',
#36 60.98 gyp info spawn args   '-Dnode_gyp_dir=/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp',
#36 60.98 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
#36 60.98 gyp info spawn args   '-Dmodule_root_dir=/opt/optimism/node_modules/usb',
#36 60.98 gyp info spawn args   '-Dnode_engine=v8',
#36 60.98 gyp info spawn args   '--depth=.',
#36 60.98 gyp info spawn args   '--no-parallel',
#36 60.98 gyp info spawn args   '--generator-output',
#36 60.98 gyp info spawn args   'build',
#36 60.98 gyp info spawn args   '-Goutput_dir=.'
#36 60.98 gyp info spawn args ]
#36 60.98 gyp info spawn make
#36 60.98 gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
#36 60.98 make: Entering directory '/opt/optimism/node_modules/usb/build'
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/core.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/io.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
#36 60.98 ../libusb/libusb/os/linux_udev.c:40:10: fatal error: libudev.h: No such file or directory
#36 60.98    40 | #include <libudev.h>
#36 60.98       |          ^~~~~~~~~~~
#36 60.98 compilation terminated.
#36 60.98 make: *** [libusb.target.mk:150: Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
#36 60.98 make: Leaving directory '/opt/optimism/node_modules/usb/build'
#36 60.98 gyp ERR! build error
#36 60.98 gyp ERR! stack Error: `make` failed with exit code: 2
#36 60.98 gyp ERR! stack     at ChildProcess.onExit (/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/build.js:194:23)
#36 60.98 gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
#36 60.98 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
#36 60.98 gyp ERR! System Linux 5.10.104-linuxkit
#36 60.98 gyp ERR! command \"/usr/local/bin/node\" \"/opt/optimism/node_modules/.bin/node-gyp\" \"rebuild\"
#36 60.98 gyp ERR! cwd /opt/optimism/node_modules/usb
#36 60.98 gyp ERR! node -v v16.14.2
#36 60.98 gyp ERR! node-gyp -v v7.1.2
#36 60.98 gyp ERR! not ok"
#36 60.98 info This module is OPTIONAL, you can safely ignore this error
------
failed to solve: executor failed running [/bin/sh -c yarn install --frozen-lockfile && yarn cache clean]: exit code: 1
```

**Expected behavior**
Build successfully.

**Screenshots**

**System Specs:**
 - OS: macOS, Apple Silicon
 - Package Version (or commit hash): 71240b1d9db330232361f2bab7669b95874ea650

**Additional context**
n/a

**Comment by smartcontracts** [comment]
Seems to be working on Ubuntu. I don't have an Apple Silicon mac, trying to find someone who does to try this.

**Comment by smartcontracts** [comment]
Confirmed on a macbook, doing a bisect to see what's up

**Comment by smartcontracts** [comment]
Source of the issue looks to be this commit https://github.com/ethereum-optimism/optimism/commit/c19571267afcb8f02e92ddc034311bc6ff69125f

**Comment by smartcontracts** [comment]
cc @mslipper for your review later

**Comment by chrismin** [comment]
@smartcontracts thanks so much for investigating! just following up to see if there are any updates on the issue 🤗

**Comment by smartcontracts** [comment]
> @smartcontracts thanks so much for investigating! just following up to see if there are any updates on the issue hugs

No updates yet, am asking around for someone working on Optimism with access to an Apple Silicon mac to debug further. I need to see some more logs to be able to figure out exactly what's going on.

**Comment by tynes** [comment]
You should be able to pull the images without needing to build them locally if you are just trying to run the system

**Comment by chrismin** [comment]
> You should be able to pull the images without needing to build them locally if you are just trying to run the system

hey @tynes — could you describe how to do this? the README under `ops` only has instructions for using docker-compose and make to build + run Optimism locally. if there's a way to just pull down the images and run them locally without building, would love to do that!

**Comment by tynes** [comment]
> > You should be able to pull the images without needing to build them locally if you are just trying to run the system
> 
> hey @tynes — could you describe how to do this? the README under `ops` only has instructions for using docker-compose and make to build + run Optimism locally. if there's a way to just pull down the images and run them locally without building, would love to do that!

`docker compose pull`

**Comment by chrismin** [comment]
> > > You should be able to pull the images without needing to build them locally if you are just trying to run the system
> > 
> > 
> > hey @tynes — could you describe how to do this? the README under `ops` only has instructions for using docker-compose and make to build + run Optimism locally. if there's a way to just pull down the images and run them locally without building, would love to do that!
> 
> `docker compose pull`

Thank you — I was able to pull down the images.

When creating and starting the containers (`docker compose up`), there seem to be a couple intermittent issues, both related to `ops-deployer`:

1. `ops-deployer` errors while attempting to fund accounts. It logs the following, then exits:
```
✓ Not changing owner of Lib_AddressManager because it's already correctly set
✓ Funded 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 on L2 with 5000.0 ETH
✓ Funded 0x70997970C51812dc3A010C7d01b50e0d17dc79C8 on L2 with 5000.0 ETH
✓ Funded 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC on L2 with 5000.0 ETH
✓ Funded 0x976EA74026E726554dB657fA54763abd0C3a0aa9 on L2 with 5000.0 ETH
✓ Funded 0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc on L2 with 5000.0 ETH
✓ Funded 0x71bE63f3384f5fb98995898A86B02Fb2426c5788 on L2 with 5000.0 ETH
✓ Funded 0x90F79bf6EB2c4f870365E785982E1f101E93b906 on L2 with 5000.0 ETH
✓ Funded 0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65 on L2 with 5000.0 ETH
✓ Funded 0x1CBd3b2770909D4e10f157cABC84C7264073C9Ec on L2 with 5000.0 ETH
✓ Funded 0x14dC79964da2C08b23698B3D3cc7Ca32193d9955 on L2 with 5000.0 ETH
✓ Funded 0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f on L2 with 5000.0 ETH
✓ Funded 0xa0Ee7A142d267C1f36714E4a8F75612F20a79720 on L2 with 5000.0 ETH

An unexpected error occurred:
Error: ERROR processing /opt/optimism/packages/contracts/deploy/016-fund-accounts.ts:
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
    at DeploymentsManager.executeDeployScripts (/opt/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:19)
    at async DeploymentsManager.runDeploy (/opt/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at async SimpleTaskDefinition.action (/opt/optimism/node_modules/hardhat-deploy/src/index.ts:438:5)
    at async Environment._runTaskDefinition (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/opt/optimism/node_modules/hardhat-deploy/src/index.ts:584:32)
    at async Environment._runTaskDefinition (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/opt/optimism/node_modules/hardhat-deploy/src/index.ts:669:5)
    at async Environment._runTaskDefinition (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
```

2. `ops-deployer` takes too long to deploy, and other services time out while attempting to connect to it. Example output from `ops-dtl` before it exited:
```
    curl: (7) Failed to connect to deployer port 8081 after 0 ms: Connection refused
    curl: (7) Failed to connect to deployer port 8081 after 0 ms: Connection refused
    curl: (7) Failed to connect to deployer port 8081 after 0 ms: Connection refused
    curl: (7) Failed to connect to deployer port 8081 after 0 ms: Connection refused
    curl: (7) Failed to connect to deployer port 8081 after 0 ms: Connection refused
    curl: (7) Failed to connect to deployer port 8081 after 0 ms: Connection refused
    curl: (7) Failed to connect to deployer port 8081 after 0 ms: Connection refused
    curl: (7) Failed to connect to deployer port 8081 after 18548 ms: Host is unreachable
```


Any advice on how to consistently get things running locally? Thanks again!

**Comment by chrismin** [comment]
For what it's worth, I'm seeing that the images built from `develop` (commit `1f134ba1dc69201e2d0cf3b0921c580cfb9d7574`) don't have this intermittent issue and `ops-deployer` runs the deployment much more quickly.

**Comment by chrismin** [comment]
Got that working! Thank you. 

I didn't realize there was a new `ops-bedrock` to go alongside the Bedrock upgrade. Where's the best place to keep up with changes in dev setup?
