### ISSUE TITLE
L2 light node crashes with SuggestL2GasPrice not implemented

### ISSUE THREAD

**Issue by DVLP** [ethereum-optimism/optimism#2615]
I just launched optimism from ethereumoptimism/l2geth for the first time and this looks like a bug after starting it

```
geth    | ERROR[05-24|21:45:13.339] RPC method eth_gasPrice crashed: SuggestL2GasPrice not implemented
geth    | goroutine 176 [running]:
geth    | github.com/ethereum-optimism/optimism/l2geth/rpc.(*callback).call.func1()
geth    |       /go-ethereum/rpc/service.go:200 +0x89
geth    | panic({0xee7920, 0x12b72e0})
geth    |       /usr/local/go/src/runtime/panic.go:838 +0x207
geth    | github.com/ethereum-optimism/optimism/l2geth/les.(*LesApiBackend).SuggestL2GasPrice(0xfa6000?, {0xc0000a61c0?, 0xc0001d2650?})
```

docker-compose.yml
```

  geth:
    container_name: "geth"
    build:
      context: ./geth-service
      dockerfile: geth.Dockerfile
    user: "$USER:$GROUP"
    volumes:
      - ./eth:/home/gethusr/.ethereum
      - '/etc/passwd:/etc/passwd:ro'
      - '/etc/group:/etc/group:ro'
    ports:
      - 30303:30303
    command:
      [
        "--syncmode=light",
        "--nousb",
        "--ws",
        "--wsaddr=0.0.0.0",
        "--wsport=8923",
        "--wsorigins=\"*\"",
        "--maxpeers=20",
        "--light.maxpeers=20",
        "--port=30303",
        "--datadir=/home/gethusr/.optimism-main"
      ]
```

geth.Dockerfile contents
```

ARG CUSTOM_USER=gethusr
FROM ethereumoptimism/l2geth
ARG CUSTOM_USER
RUN addgroup -S "$CUSTOM_USER"
RUN adduser \
    --disabled-password \
    --gecos "" \
    --ingroup "$CUSTOM_USER" \
    "$CUSTOM_USER"
WORKDIR /home/$CUSTOM_USER
USER "$CUSTOM_USER"

```
**Expected behavior**
Not crashing

**System Specs:**
 - OS: Docker in Windows on WSL
 - Package Version (or commit hash): hash on dockerhub f1fd8ace1916

**Comment by mslipper** [comment]
Hi there,

Light nodes are not supported at this time. Please refer to https://community.optimism.io/docs/developers/build/run-a-node/ for information on how to run a node.
