### ISSUE TITLE
there is the error

### ISSUE THREAD

**Issue by malingzhao** [ethereum-optimism/optimism#2691]
\":\\\"0xcf7732\\\",\\\"toBlock\\\":\\\"0xdc09f2\\\",\\\"address\\\":\\\"0xde1fcfb0851916ca5101820a69b13a4e276bd81f\\\",\\\"topics\\\":[\\\"0x9416a153a346f93d95f94b064ae3f148b6460473c6e82b3f9fc2521b873fcd6c\\\",\\\"0x02b616af23339f1e031e76333e2d5b1c3067beb78578c961911872cc2127ef8b\\\"]}],\\\"id\\\":53,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", serverError={\"code\":\"ECONNRESET\"}, url=\"http://172.16.3.190:8545\", code=SERVER_ERROR, version=web/5.6.1)","stack":"Error: missing response (requestBody=\"{\\\"method\\\":\\\"eth_getLogs\\\",\\\"params\\\":[{\\\"fromBlock\\\":\\\"0xcf7732\\\",\\\"toBlock\\\":\\\"0xdc09f2\\\",\\\"address\\\":\\\"0xde1fcfb0851916ca5101820a69b13a4e276bd81f\\\",\\\"topics\\\":[\\\"0x9416a153a346f93d95f94b064ae3f148b6460473c6e82b3f9fc2521b873fcd6c\\\",\\\"0x02b616af23339f1e031e76333e2d5b1c3067beb78578c961911872cc2127ef8b\\\"]}],\\\"id\\\":53,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", serverError={\"code\":\"ECONNRESET\"}, url=\"http://172.16.3.190:8545\", code=SERVER_ERROR, version=web/5.6.1)\n    at Logger.makeError (/data/optimsim/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)\n    at Logger.throwError (/data/optimsim/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)\n    at /data/optimsim/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/src.ts/index.ts:280:28\n    at step (/data/optimsim/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:33:23)\n    at Object.throw (/data/optimsim/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:14:53)\n    at rejected (/data/optimsim/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","code":"SERVER_ERROR"},"msg":"Caught an unhandled error"}

**Comment by smartcontracts** [comment]
It looks like the connection to your L1 node broke, is your L1 node working?
