### ISSUE TITLE
Crash: replica-healthcheck

### ISSUE THREAD

**Issue by breezytm** [ethereum-optimism/optimism#2798]
**Describe the bug**
The ``replica-healthcheck`` container is constantly crashing. Both ``data-transport-layer`` and ``l2geth-replica`` seem to be running. The only deviation from the documentation is I changed the ports in``replica-shared.yml`` from 8545, and 8546 to 8555 and 8556. Both ports are currently being used by Ethereum mainnet on the same host. A little help would be nice 🙏

```replica-healthcheck_1   | > @eth-optimism/replica-healthcheck@1.1.2 start
replica-healthcheck_1   | > ts-node ./src/service
replica-healthcheck_1   | 
replica-healthcheck_1   | /opt/optimism/packages/common-ts/src/base-service/base-service-v2.ts:303
replica-healthcheck_1   |         throw new Error(`missing required option: ${optionName}`)
replica-healthcheck_1   |               ^
replica-healthcheck_1   | Error: missing required option: referenceRpcProvider
replica-healthcheck_1   |     at new BaseServiceV2 (/opt/optimism/packages/common-ts/src/base-service/base-service-v2.ts:303:15)
replica-healthcheck_1   |     at new HealthcheckService (/opt/optimism/packages/replica-healthcheck/src/service.ts:34:5)
replica-healthcheck_1   |     at Object.<anonymous> (/opt/optimism/packages/replica-healthcheck/src/service.ts:208:19)
replica-healthcheck_1   |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
replica-healthcheck_1   |     at Module.m._compile (/opt/optimism/node_modules/ts-node/src/index.ts:1310:23)
replica-healthcheck_1   |     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
replica-healthcheck_1   |     at Object.require.extensions.<computed> [as .ts] (/opt/optimism/node_modules/ts-node/src/index.ts:1313:12)
replica-healthcheck_1   |     at Module.load (node:internal/modules/cjs/loader:981:32)
replica-healthcheck_1   |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
replica-healthcheck_1   |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
replica-healthcheck_1   | npm ERR! Lifecycle script `start` failed with error: 
replica-healthcheck_1   | npm ERR! Error: command failed 
replica-healthcheck_1   | npm ERR!   in workspace: @eth-optimism/replica-healthcheck@1.1.2 
replica-healthcheck_1   | npm ERR!   at location: /opt/optimism/packages/replica-healthcheck 
op-replica_replica-healthcheck_1 exited with code 1```

**Comment by sing1ee** [comment]
same issue
```shell
L2GETH_IMAGE_TAG=0.5.22
DTL_IMAGE_TAG=0.5.36
HC_IMAGE_TAG=1.1.2
```

**Comment by sing1ee** [comment]
```shell
 // Make sure all options are defined.
    for (const [optionName, optionSpec] of Object.entries(params.optionsSpec)) {
      if (
        **optionSpec.default === undefined** &&
        this.options[optionName] === undefined
      ) {
        throw new Error(`missing required option: ${optionName}`)
      }
    }

```
But
```shell
referenceRpcProvider: {
          validator: validators.provider,
          desc: 'Provider for interacting with L1',
          secret: true,
        },
```
There is no **referenceRpcProvider.default**

**Comment by sing1ee** [comment]
```shell
    // Make sure all options are defined.
    for (const [optionName, optionSpec] of Object.entries(params.optionsSpec)) {
      if (
        optionSpec.default === undefined &&
        this.options[optionName] === undefined
      ) {
        throw new Error(`missing required option: ${optionName}`)
      }
    }
```
referenceRpcProvider.default is always undefined

**Comment by smartcontracts** [comment]
cc @optimisticben we need to update the config to include the correct environment variables by default. I think the config is still stuck on the old version of the replica healthcheck and doesn't include all of the environment variables that you need for the new version.

@sing1ee @breezytm you likely just need to set the following environment variables:

```
HEALTHCHECK__REFERENCE_RPC_PROVIDER=<reference provider goes here>
HEALTHCHECK__TARGET_RPC_PROVIDER=<your node RPC goes here>
```

**Comment by breezytm** [comment]
Looking at the ``replica-healthcheck.env``, it seems like these values are set. Do I need to update the file?

```REPLICA_HEALTHCHECK__ETH_NETWORK=mainnet
REPLICA_HEALTHCHECK__L2GETH_IMAGE_TAG=0.4.8
REPLICA_HEALTHCHECK__ETH_NETWORK_RPC_PROVIDER=http://sequencer.default:8545
REPLICA_HEALTHCHECK__ETH_REPLICA_RPC_PROVIDER=http://l2geth-replica:8545```

**Comment by optimisticben** [comment]
Created a PR with the new values required for replica-healthcheck > v1.

For mainnet, you should add to your .env
```
HEALTHCHECK__REFERENCE_RPC_PROVIDER=https://mainnet.optimism.io
HEALTHCHECK__TARGET_RPC_PROVIDER=http://l2geth-replica:8545
```

**Comment by breezytm** [comment]
Adding these two values to the ``.env`` file solved the issue. Thanks 👍
