### ISSUE TITLE
panic: runtime error: integer divide by zero when trying to bring up l2

### ISSUE THREAD

**Issue by danielvladco** [ethereum-optimism/optimism#3442]
**Describe the bug**
when running `docker-compose up l2` from `ops-bedrock` directory the node crashes with a panic
```
l2_1           | panic: runtime error: integer divide by zero
l2_1           | 
l2_1           | goroutine 82 [running]:
l2_1           | github.com/ethereum/go-ethereum/consensus/misc.CalcBaseFee(0xc0004a6c40, 0xc001206240)
l2_1           |        github.com/ethereum/go-ethereum/consensus/misc/eip1559.go:61 +0x5e5
l2_1           | github.com/ethereum/go-ethereum/miner.(*worker).prepareWork(0xc00051e900, 0xc0012839e0)
l2_1           |        github.com/ethereum/go-ethereum/miner/worker.go:1012 +0x6ec
l2_1           | github.com/ethereum/go-ethereum/miner.(*worker).commitWork(0xc00051e900, 0xc000295b7c?, 0x0, 0x6320713f)
l2_1           |        github.com/ethereum/go-ethereum/miner/worker.go:1120 +0x132
l2_1           | github.com/ethereum/go-ethereum/miner.(*worker).mainLoop(0xc00051e900)
l2_1           |        github.com/ethereum/go-ethereum/miner/worker.go:534 +0x76a
l2_1           | created by github.com/ethereum/go-ethereum/miner.newWorker
l2_1           |        github.com/ethereum/go-ethereum/miner/worker.go:293 +0x765
```
**To Reproduce**
run `foundryup`
run `yarn install`
run `yarn build`
run `make devnet-up`

**Expected behavior**
Bring up a fresh optimism environment with `l1`, `l2`, `op-node`, `op-proposer` and `op-batcher` services

**Screenshots**

**System Specs:**
 - OS: macOS Monterey v 12.6
 - Package Version (or commit hash): f772f66cfcb59e57d43bdd0419baf5a5ee96228e

**Additional context**
The division by 0 happens here: https://github.com/ethereum/go-ethereum/blob/master/consensus/misc/eip1559.go#L61
It is weird since ElasticityMultiplier is a constant set to 2. Is there a process that modifies the compiled binary and changes this value?

**Comment by danielvladco** [comment]
`make devnet-clean` worked plus I checked out the latest changes
