### ISSUE TITLE
DTL cannot running with local ETH endpoint

### ISSUE THREAD

**Issue by sotatek-manhnguyen8** [ethereum-optimism/optimism#3507]
Hello there,

I'm starting to run a new RPC node. I use L1 syncing with my local ETH. But it occurs this error.
This is my log:

```
{"level":30,"time":1663668219276,"msg":"Service is starting..."}
{"level":30,"time":1663668219276,"msg":"Service is initializing..."}
{"level":30,"time":1663668219277,"msg":"Initializing L1 Data Transport Service..."}
{"level":30,"time":1663668219288,"msg":"L2 chain ID is: 10"}
{"level":30,"time":1663668219288,"msg":"BSS HF1 will activate at: 2824317"}
{"level":30,"time":1663668219292,"msg":"Service is initializing..."}
{"level":30,"time":1663668219297,"defaultBackend":"l1","l1GasPriceBackend":"l1","msg":"HTTP Server Options"}
{"level":30,"time":1663668219297,"url":"http://eth-free-arch-01:8545","msg":"HTTP Server L1 RPC Provider initialized"}
{"level":30,"time":1663668219297,"url":"https://mainnet.optimism.io/","msg":"HTTP Server L2 RPC Provider initialized"}
{"level":30,"time":1663668219297,"msg":"Service has initialized."}
{"level":30,"time":1663668219297,"msg":"Service is initializing..."}
{"level":30,"time":1663668219297,"addressManager":"0xdE1FCfB0851916CA5101820A69b13a4E276bd81F","msg":"Using AddressManager"}
{"level":30,"time":1663668219389,"startingL1BlockNumber":13596466,"msg":"Starting sync"}
{"level":30,"time":1663668219394,"msg":"Service has initialized."}
{"level":30,"time":1663668219394,"msg":"Service has initialized."}
{"level":30,"time":1663668219394,"msg":"Service is starting..."}
{"level":30,"time":1663668219394,"msg":"Service is starting..."}
{"level":30,"time":1663668219395,"host":"0.0.0.0","port":7878,"msg":"Server started and listening"}
{"level":30,"time":1663668219396,"msg":"Service has started"}
{"level":30,"time":1663668219399,"highestSyncedL1Block":13626395,"targetL1Block":13628395,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1663668220023,"eventName":"TransactionEnqueued","numEvents":286,"durationMs":67,"msg":"Processed events"}
{"level":40,"time":1663668220692,"message":"SequencerBatchAppended: missing event: SequencerBatchAppended","msg":"recovering from a missing event"}
Well, that's that. We ran into a fatal error. Here's the dump. Goodbye!
/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:164
                        throw new Error(`unable to recover from missing event`);
                              ^
Error: unable to recover from missing event
    at L1IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:164:31)
    at async L1IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)
    at async Promise.all (index 1)
    at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:69:13)
    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)
    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:77:9
```

It is highly appreciated for your help. Thanks

**Comment by sotatek-manhnguyen8** [comment]
Here is my data transport layer env:

```
DATA_TRANSPORT_LAYER__ADDRESS_MANAGER: "0xdE1FCfB0851916CA5101820A69b13a4E276bd81F"
DATA_TRANSPORT_LAYER__SYNC_FROM_L1: "true"
DATA_TRANSPORT_LAYER__SYNC_FROM_L2: "false"
DATA_TRANSPORT_LAYER__L1_START_HEIGHT: "13596466"
DATA_TRANSPORT_LAYER__CONFIRMATIONS: "12"
DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS: "true"
DATA_TRANSPORT_LAYER__DB_PATH: "/db"
DATA_TRANSPORT_LAYER__ENABLE_METRICS: "true"
DATA_TRANSPORT_LAYER__ETH_NETWORK_NAME: "mainnet"
DATA_TRANSPORT_LAYER__L2_CHAIN_ID: "10"
DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL: "2000"
DATA_TRANSPORT_LAYER__NODE_ENV: "production"
DATA_TRANSPORT_LAYER__POLLING_INTERVAL: "500"
DATA_TRANSPORT_LAYER__SENTRY_TRACE_RATE: "0.05"
DATA_TRANSPORT_LAYER__SERVER_HOSTNAME: "0.0.0.0"
DATA_TRANSPORT_LAYER__SERVER_PORT: "7878"
DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL: "1000"
NETWORK_NAME: "mainnet"
DATA_TRANSPORT_LAYER__DEFAULT_BACKEND: "l1"
DATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND: "l1"
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: "http://eth-free-arch-01:8545"


ETH_NETWORK: "mainnet"
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: "https://mainnet.optimism.io/"
ROLLUP_BACKEND: "l1"
```

**Comment by smartcontracts** [comment]
Strange. Can you check if this same configuration works when your L1 RPC endpoint is a node provider like Alchemy or Infura?

**Comment by smartcontracts** [comment]
> I'm using Erigon+Lighthouse for ETH RPC node, all methods with curl still working properly, such as eth_blockNumber, eth_syncing, ...

Ah yeah I just mean temporarily try using `DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=<some alchemy node>` just to see if the rest of your configuration is correct.

**Comment by sotatek-manhnguyen8** [comment]
@smartcontracts Ah, yeah, when using Infura RPC, My Optimism node works well.

**Comment by davidzshi** [comment]
@smartcontracts I'm having the same issue with an identical setup as @sotatek-manhnguyen8, using an archive Erigon node with RPC methods all working. Any idea on why the managed service RPC works and a self-hosted node doesn't?

**Comment by smartcontracts** [comment]
Hmmm.... I need to investigate. @davidzshi are you observing the exact same issue? `unable to recover from missing event`?

**Comment by davidzshi** [comment]
I just retried and the sync from a self-hosted node is now running successfully. I didn't do anything differently excepted update the docker images, so I'm assuming there was a fix implemented there.

**Comment by smartcontracts** [comment]
Ok I'll keep this open for a few more days. If no one else runs into this issue then we can close. Glad it's syncing properly now!
