### ISSUE TITLE
Error at deploying contracts

### ISSUE THREAD

**Issue by cyborgdennett** [ethereum-optimism/optimism#3515]
**Describe the bug**
While running `npx hardhat delpoy --network xxx` on optimism/packages/contracts. I get the following error.

`TypeError: Cannot read properties of null (reading 'gasUsed') `
**To Reproduce**
1. Go to optimism/packages/contracts/deploy-config
2. Add new deploy file
3. Add the network to hardhat.config.ts  
```
xxx: {
      chainId: 31337,
      url: 'http://127.0.0.1:9545',
      accounts: [privateKey],
},
```
4. Run geth --datadir data init genesis.json
5. Run an ethereum network on geth --datadir data --http 0.0.0.0 --http.port 9545
6. export private key
7. run `npx hardhat deploy --network xxx`
8. Receive error

**Expected behavior**
Deploy the contracts to L1

**Screenshots**
deploy-config/xxx.ts. This is a copy of local.ts ( Possibly this is the problem, but I don't know why)
```
const config = {
  l1BlockTimeSeconds: 5,
  l2BlockGasLimit: 15_000_000,
  l2ChainId: 17,
  ctcL2GasDiscountDivisor: 32,
  ctcEnqueueGasCost: 60_000,
  sccFaultProofWindowSeconds: 0,
  sccSequencerPublishWindowSeconds: 12592000,
  ovmSequencerAddress: '0x70997970c51812dc3a010c7d01b50e0d17dc79c8',
  ovmProposerAddress: '0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc',
  ovmBlockSignerAddress: '0x00000398232E2064F896018496b4b44b3D62751F',
  ovmFeeWalletAddress: '0x391716d440c151c42cdf1c95c1d83a5427bca52c',
  ovmAddressManagerOwner: '0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266',
  ovmGasPriceOracleOwner: '0x9965507d1a55bcc2695c58ba16fb37d819b0a4dc',
}

export default config
```
genesis file
```
{
    "config": {
        "chainId": 31337,
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "petersburgBlock": 0,
        "istanbulBlock": 0,
        "berlinBlock": 0,
        "londonBlock": 0,
        "clique": {
            "period": 5,
            "epoch": 30000
        }
    },
    "difficulty": "1",
    "gasLimit": "32000000",
    "nonce": "0x5671345102a78142",
    "extradata": "0x0000000000000000000000000000000000000000000000000000000000000000872425436273C68F0720E8b06C845A17A17853b90000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "alloc": {
        "872425436273C68F0720E8b06C845A17A17853b9": {
            "balance": "115792089237316195423570985008687907853269984665640564039457584007913129639935"
        }
    }
}

```

The error
```
✅ All Contracts have been checked for missing Natspec comments
deploying "Lib_AddressManager" (tx: 0x208d101e317d80097aa81cf687eb7066a6e99a1b2f142010f16f028955e9fb54)...An unexpected error occurred:

Error: ERROR processing /home/casper/optimism/packages/contracts/deploy/001-Lib_AddressManager.deploy.ts:
TypeError: Cannot read properties of null (reading 'gasUsed')
    at Object.tx.wait (/home/casper/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:559:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _deploy (/home/casper/optimism/node_modules/hardhat-deploy/src/helpers.ts:667:21)
    at async _deployOne (/home/casper/optimism/node_modules/hardhat-deploy/src/helpers.ts:1004:16)
    at async Object.deployFn [as func] (/home/casper/optimism/packages/contracts/deploy/001-Lib_AddressManager.deploy.ts:12:3)
    at async DeploymentsManager.executeDeployScripts (/home/casper/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1219:22)
    at async DeploymentsManager.runDeploy (/home/casper/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at async SimpleTaskDefinition.action (/home/casper/optimism/node_modules/hardhat-deploy/src/index.ts:438:5)
    at async Environment._runTaskDefinition (/home/casper/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/home/casper/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at DeploymentsManager.executeDeployScripts (/home/casper/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DeploymentsManager.runDeploy (/home/casper/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at async SimpleTaskDefinition.action (/home/casper/optimism/node_modules/hardhat-deploy/src/index.ts:438:5)
    at async Environment._runTaskDefinition (/home/casper/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/home/casper/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async SimpleTaskDefinition.action (/home/casper/optimism/node_modules/hardhat-deploy/src/index.ts:584:32)
    at async Environment._runTaskDefinition (/home/casper/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/home/casper/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async SimpleTaskDefinition.action (/home/casper/optimism/node_modules/hardhat-deploy/src/index.ts:669:5)
```
**System Specs:**
 - OS:
 - Package Version (or commit hash):

**Additional context**

**Comment by cyborgdennett** [comment]
Could it be something wrong with the hardhat-deploy module?

**Comment by cyborgdennett** [comment]
Hello, The reason this failed is because in the deploy-config, `numDeployConfirmations` is not set. For future people trying to deploy this to an not-hardhat network, set this to atleast 1.

**Comment by cyborgdennett** [comment]
I think it would be handy to include this in the docs somewhere.
