### ISSUE TITLE
Fault Detector - Dependency on `.../package.json` (version)

### ISSUE THREAD

**Issue by andreclaro** [ethereum-optimism/optimism#3935]
**Describe the bug**
A dependency on .../package.json , makes it not possible to run using just the fault-detector dist files: `node dist/src/service.js` 

https://github.com/ethereum-optimism/optimism/blob/develop/packages/fault-detector/src/service.ts#L42

**Additional context**

```
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '../package.json'
Require stack:
- /faultdetector/dist/src/service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new FaultDetector (/faultdetector/dist/src/service.js:16:22)
    at Object.<anonymous> (/faultdetector/dist/src/service.js:234:21)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/faultdetector/dist/src/service.js' ]
}
```

**Comment by smartcontracts** [comment]
Completed in #3934
