### ISSUE TITLE
Batch submitter is reverting when calling `getNextPendingQueueElement`

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/optimism#455]
**Describe the bug**

**To Reproduce**
1. Hardhat fork mainnet
2. Impersonate account for mainnet batch submitter address `0xfd7D4de366850C08EE2CBa32d851385A3071Ec8D`
3. Run transaction batch submitter with mainnet config. (Most configs should work)

**Expected behavior**
The batch should be submitted.

**Logs**

```
$ node ./exec/run-batch-submitter.js
{"level":30,"time":1618331006619,"msg":"Starting batch submitter..."}
{"level":30,"time":1618331006738,"batchSubmitterAddress":"0xfd7D4de366850C08EE2CBa32d851385A3071Ec8D","addressManagerAddress":"0x1De8CFD4C1A486200286073aE91DE6e8099519f1","msg":"Configured batch submitter addresses"}
{"level":30,"time":1618331011382,"address":"0xed2701f7135eab0D7ca02e6Ab634AD6CbE159Ffb","msg":"Initialized new CTC"}
{"level":30,"time":1618331011393,"address":"0xfd7D4de366850C08EE2CBa32d851385A3071Ec8D","ether":"2.569769098380553566","msg":"Checked balance"}
{"level":20,"time":1618331014882,"blockNo":126004,"msg":"Fetching L2BatchElement"}
{"level":20,"time":1618331014883,"blockNo":126005,"msg":"Fetching L2BatchElement"}
(node:13858) UnhandledPromiseRejectionWarning: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":54,\"error\":{\"code\":-32603,\"message\":\"Transaction reverted without a reason\"}}", error={"code":-32603}, requestBody="{\"method\":\"eth_call\",\"params\":[{\"from\":\"0xfd7d4de366850c08ee2cba32d851385a3071ec8d\",\"to\":\"0xed2701f7135eab0d7ca02e6ab634ad6cbe159ffb\",\"data\":\"0xf722b41a\"},\"latest\"],\"id\":54,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:8545", code=SERVER_ERROR, version=web/5.0.13)
    at Logger.makeError (/Users/kflizzle/workspace/batch-submitter/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/Users/kflizzle/workspace/batch-submitter/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at /Users/kflizzle/workspace/batch-submitter/node_modules/@ethersproject/web/src.ts/index.ts:284:28
    at step (/Users/kflizzle/workspace/batch-submitter/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/Users/kflizzle/workspace/batch-submitter/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/Users/kflizzle/workspace/batch-submitter/node_modules/@ethersproject/web/lib/index.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13858) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13858) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{"level":20,"time":1618331015874,"ele":{"stateRoot":"0x68ee0c3bd4c4aa00508863597f48b6493cd40f47707497e9305ef4e865fb88b2","isSequencerTx":true,"sequencerTxType":1,"txData":{"sig":{"v":0,"r":"0x59e15499eafe632a02c591fef0d0e572752af35035a2437e5864df28d4e41088","s":"0x7f58a73fe0135ed17d23e1cf950a16e2f13db83fcd23f279dfef46e424274053"},"gasLimit":8999999,"gasPrice":0,"nonce":33,"target":"0x8700dAec35aF8Ff88c16BdF0418774CB3D7599B4","data":"0x9741fb22","type":1},"timestamp":1618010413,"blockNumber":12208590},"msg":"Verifying batch element"}
{"level":20,"time":1618331015874,"ele":{"stateRoot":"0x08e14d043243ec376066e1af494cadd9208330ffacb4ce00a0df5450cb53d6d7","isSequencerTx":true,"sequencerTxType":1,"txData":{"sig":{"v":1,"r":"0x0b796a74a8ae3bda9c7e21522f3b4d51af664a8f90c8ca987237ec2ee212158a","s":"0x22c2a7f2494e73e9fe43f45ca22cc8c5952e3b1a4b74810d5eab411653c56990"},"gasLimit":8999999,"gasPrice":0,"nonce":34,"target":"0x8700dAec35aF8Ff88c16BdF0418774CB3D7599B4","data":"0x9741fb22","type":1},"timestamp":1618010413,"blockNumber":12208590},"msg":"Verifying batch element"}
{"level":30,"time":1618331015875,"batchSizeInBytes":231,"lastBatchSubmissionTimestamp":0,"currentTimestamp":1618331015875,"msg":"Timeout reached, proceeding with batch submission."}
{"level":20,"time":1618331015875,"calldata":{"shouldStartAtElement":126003,"totalElementsToAppend":2,"contexts":[{"numSequencedTransactions":2,"numSubsequentQueueTransactions":0,"timestamp":1618010413,"blockNumber":12208590}],"transactions":["0x0159e15499eafe632a02c591fef0d0e572752af35035a2437e5864df28d4e410887f58a73fe0135ed17d23e1cf950a16e2f13db83fcd23f279dfef46e4242740530089543f0000000000218700dAec35aF8Ff88c16BdF0418774CB3D7599B49741fb22","0x010b796a74a8ae3bda9c7e21522f3b4d51af664a8f90c8ca987237ec2ee212158a22c2a7f2494e73e9fe43f45ca22cc8c5952e3b1a4b74810d5eab411653c569900189543f0000000000228700dAec35aF8Ff88c16BdF0418774CB3D7599B49741fb22"]},"msg":"Submitting batch."}
{"level":20,"time":1618331015890,"msg":"Waiting for receipt..."}
{"level":50,"time":1618331016897,"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":63,\"error\":{\"code\":-32603,\"message\":\"Transaction reverted without a reason\"}}","error":{"code":-32603},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x8d8f9fc00\",\"from\":\"0xfd7d4de366850c08ee2cba32d851385a3071ec8d\",\"to\":\"0xed2701f7135eab0d7ca02e6ab634ad6cbe159ffb\",\"data\":\"0xd0f89344000001ec33000002000001000002000000006070e12d0000ba49ce0000630159e15499eafe632a02c591fef0d0e572752af35035a2437e5864df28d4e410887f58a73fe0135ed17d23e1cf950a16e2f13db83fcd23f279dfef46e4242740530089543f0000000000218700daec35af8ff88c16bdf0418774cb3d7599b49741fb22000063010b796a74a8ae3bda9c7e21522f3b4d51af664a8f90c8ca987237ec2ee212158a22c2a7f2494e73e9fe43f45ca22cc8c5952e3b1a4b74810d5eab411653c569900189543f0000000000228700daec35af8ff88c16bdf0418774cb3d7599b49741fb22\"}],\"id\":63,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://localhost:8545"},"tx":{"to":{},"data":"0xd0f89344000001ec33000002000001000002000000006070e12d0000ba49ce0000630159e15499eafe632a02c591fef0d0e572752af35035a2437e5864df28d4e410887f58a73fe0135ed17d23e1cf950a16e2f13db83fcd23f279dfef46e4242740530089543f0000000000218700dAec35aF8Ff88c16BdF0418774CB3D7599B49741fb22000063010b796a74a8ae3bda9c7e21522f3b4d51af664a8f90c8ca987237ec2ee212158a22c2a7f2494e73e9fe43f45ca22cc8c5952e3b1a4b74810d5eab411653c569900189543f0000000000228700dAec35aF8Ff88c16BdF0418774CB3D7599B49741fb22","nonce":632,"gasPrice":38000000000,"from":"0xfd7D4de366850C08EE2CBa32d851385A3071Ec8D","gasLimit":{},"chainId":{}},"stack":"Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={\"reason\":\"processing response error\",\"code\":\"SERVER_ERROR\",\"body\":\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":63,\\\"error\\\":{\\\"code\\\":-32603,\\\"message\\\":\\\"Transaction reverted without a reason\\\"}}\",\"error\":{\"code\":-32603},\"requestBody\":\"{\\\"method\\\":\\\"eth_estimateGas\\\",\\\"params\\\":[{\\\"gasPrice\\\":\\\"0x8d8f9fc00\\\",\\\"from\\\":\\\"0xfd7d4de366850c08ee2cba32d851385a3071ec8d\\\",\\\"to\\\":\\\"0xed2701f7135eab0d7ca02e6ab634ad6cbe159ffb\\\",\\\"data\\\":\\\"0xd0f89344000001ec33000002000001000002000000006070e12d0000ba49ce0000630159e15499eafe632a02c591fef0d0e572752af35035a2437e5864df28d4e410887f58a73fe0135ed17d23e1cf950a16e2f13db83fcd23f279dfef46e4242740530089543f0000000000218700daec35af8ff88c16bdf0418774cb3d7599b49741fb22000063010b796a74a8ae3bda9c7e21522f3b4d51af664a8f90c8ca987237ec2ee212158a22c2a7f2494e73e9fe43f45ca22cc8c5952e3b1a4b74810d5eab411653c569900189543f0000000000228700daec35af8ff88c16bdf0418774cb3d7599b49741fb22\\\"}],\\\"id\\\":63,\\\"jsonrpc\\\":\\\"2.0\\\"}\",\"requestMethod\":\"POST\",\"url\":\"http://localhost:8545\"}, tx={\"to\":{},\"data\":\"0xd0f89344000001ec33000002000001000002000000006070e12d0000ba49ce0000630159e15499eafe632a02c591fef0d0e572752af35035a2437e5864df28d4e410887f58a73fe0135ed17d23e1cf950a16e2f13db83fcd23f279dfef46e4242740530089543f0000000000218700dAec35aF8Ff88c16BdF0418774CB3D7599B49741fb22000063010b796a74a8ae3bda9c7e21522f3b4d51af664a8f90c8ca987237ec2ee212158a22c2a7f2494e73e9fe43f45ca22cc8c5952e3b1a4b74810d5eab411653c569900189543f0000000000228700dAec35aF8Ff88c16BdF0418774CB3D7599B49741fb22\",\"nonce\":632,\"gasPrice\":38000000000,\"from\":\"0xfd7D4de366850C08EE2CBa32d851385A3071Ec8D\",\"gasLimit\":{},\"chainId\":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.0.12)\n    at Logger.makeError (/Users/kflizzle/workspace/batch-submitter/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)\n    at Logger.throwError (/Users/kflizzle/workspace/batch-submitter/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)\n    at /Users/kflizzle/workspace/batch-submitter/node_modules/@ethersproject/abstract-signer/src.ts/index.ts:204:31\n    at process._tickCallback (internal/process/next_tick.js:68:7)","type":"Error","msg":"Error submitting batch"}
{"level":30,"time":1618331016898,"msg":"Retrying..."}
```

**Comment by gakonst** [comment]
I'm not able to repro with the steps given in https://github.com/ethereum-optimism/optimism/compare/fix/mainnet-submitter

```
node exec/run-batch-submitter.js
{"level":30,"time":1618335136351,"msg":"Starting batch submitter..."}
{"level":30,"time":1618335136370,"batchSubmitterAddress":"0xfd7D4de366850C08EE2CBa32d851385A3071Ec8D","addressManagerAddress":"0x1De8CFD4C1A486200286073aE91DE6e8099519f1","msg":"Configured batch submitter addresses"}
{"level":30,"time":1618335141371,"address":"0xed2701f7135eab0D7ca02e6Ab634AD6CbE159Ffb","msg":"Initialized new CTC"}
{"level":30,"time":1618335141378,"address":"0xfd7D4de366850C08EE2CBa32d851385A3071Ec8D","ether":"2.569769098380553566","msg":"Checked balance"}
{"level":30,"time":1618335141378,"l2ChainId":"0xa","batchSubmitterAddress":"0xfd7D4de366850C08EE2CBa32d851385A3071Ec8D","msg":"Readying to submit next batch..."}
{"level":30,"time":1618335141378,"msg":"Getting batch start and end for transaction batch submitter..."}
{"level":30,"time":1618335144818,"startBlock":126004,"msg":"Retrieved start block number from CTC"}
{"level":30,"time":1618335145281,"endBlock":2056,"msg":"Retrieved end block number from L2 sequencer"}
{"level":50,"time":1618335145281,"msg":"More chain elements in L1 (126004) than in the L2 node (2056).\n                   This shouldn't happen because we don't submit batches if the sequencer is syncing."}
{"level":30,"time":1618335145281,"msg":"No txs to submit. Skipping batch submission...
```

**Comment by karlfloersch** [comment]
Sorry @gakonst that's because the `AddressManagerAddress` that I supplied is incorrect -- my bad! 

The correct address is `0xd3EeD86464Ff13B4BFD81a3bB1e753b7ceBA3A39`. I'll repro in your branch though

**Comment by karlfloersch** [comment]
@gakonst just pushed to your branch to repo the bug. It's a different error than I originally got because I had the wrong config originally--whoops!

**Comment by karlfloersch** [comment]
Ok it looks like it's a monotonicity violation 😢 . You can reproduce with @gakonst 's awesome branch - https://github.com/ethereum-optimism/optimism/compare/fix/mainnet-submitter

The commands to run:

```
yarn hardhat node --fork https://mainnet.infura.io/v3/<your api key>
yarn build
source ./batchEnv
node exec/run-batch-submitter.js
```

**Comment by snario** [comment]
[logs2.txt](https://github.com/ethereum-optimism/optimism/files/6307104/logs2.txt)

I ran this locally and produced the above logs.

**Comment by snario** [comment]
The batch submitter is also functioning after a restart. You can see that it is submitting batches now; https://etherscan.io/address/0xfd7d4de366850c08ee2cba32d851385a3071ec8d

**Comment by snario** [comment]
We think that the flaky integration test #430 may be caused by issues related to this bug.

**Comment by smartcontracts** [comment]
Does this still happen? cc @karlfloersch
