### ISSUE TITLE
Testnet can't sync, stuck in block number 4061223

### ISSUE THREAD

**Issue by UranusLin** [ethereum-optimism/optimism#4739]
**Describe the bug**

I run test net in docker-compose, and whether sync from L1 or L2 will be stuck in bock number 4061223, and if sync from L2, DTL will show this error. 

```
{"level":50,"time":1674100725713,"extra":{"message":"TypeError: blocks is not iterable","stack":"TypeError: blocks is not iterable\n    at L2IngestionService._syncSequencerBlocks (/opt/optimism/packages/data-transport-layer/dist/src/services/l2-ingestion/service.js:224:29)\n    at async L2IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l2-ingestion/service.js:147:17)\n    at async L2IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async Promise.all (index 2)\n    at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:69:13)\n    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:78:9"},"msg":"Caught an unhandled error"}
{"level":30,"time":1674100726463,"fromBlock":1,"toBlock":1001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
```

How can I solve this problem, or can I skip this block number to continue syncing?

**To Reproduce**

.env
```
COMPOSE_PROJECT_NAME=op-replica
COMPOSE_FILE=replica.yml:replica-shared.yml:replica-toml.yml
ETH_NETWORK=goerli
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=L1 RPC server
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://goerli.optimism.io
REPLICA_HEALTHCHECK__ETH_NETWORK_RPC_PROVIDER=https://goerli.optimism.io
SEQUENCER_CLIENT_HTTP=https://goerli.optimism.io
SHARED_ENV_PATH=../envs/goerli-devnet
GCMODE=full
L2GETH_IMAGE_TAG=0.5.31
DTL_IMAGE_TAG=0.5.50
HC_IMAGE_TAG=1.2.0
L2GETH_HTTP_PORT=9991
L2GETH_WS_PORT=9992
DTL_PORT=7878
GETH_INIT_SCRIPT=check-for-chaindata-berlin.sh
HEALTHCHECK__REFERENCE_RPC_PROVIDER=https://goerli.optimism.io
HEALTHCHECK__TARGET_RPC_PROVIDER=http://l2geth-replica:8545

RESTART=unless-stopped

# Sync source
ROLLUP_BACKEND=l1
DATA_TRANSPORT_LAYER__DEFAULT_BACKEND=l1
DATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND=l1
DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
DATA_TRANSPORT_LAYER__SYNC_FROM_L2=false
```

run in docker-composte

**Expected behavior**

success sync 

**Screenshots**

![截圖 2023-01-19 下午12 15 17](https://user-images.githubusercontent.com/5743898/213353927-34159119-a2bc-4b7b-a288-d9de9cd9b348.png)

**System Specs:**
 - OS:
 - Package Version (or commit hash):

**Additional context**

**Comment by qbzzt** [comment]
Did you update to Bedrock? See
https://community.optimism.io/docs/developers/bedrock/node-operator-guide/

**Comment by Salexber** [comment]
https://oplabs.notion.site/Running-a-Node-eda545c730e64b44b762ab12e93296aa
The instruction given in the example is not perfect. Is there a clear instruction for raising the bedrock in the container?

**Comment by smartcontracts** [comment]
Goerli was upgraded to Bedrock last week. The legacy nodes halted at 4061223, you will need to upgrade to Bedrock to continue.

**Comment by UranusLin** [comment]
Sorry for the late reply; how to set Bedrock in docker-compose? It needs to run a new Bedrock docker container? or setting in .env 
```
COMPOSE_PROJECT_NAME=op-replica
COMPOSE_FILE=replica.yml:replica-shared.yml:replica-toml.yml
ETH_NETWORK=goerli
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=L1 RPC server
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://goerli.optimism.io
REPLICA_HEALTHCHECK__ETH_NETWORK_RPC_PROVIDER=https://goerli.optimism.io
SEQUENCER_CLIENT_HTTP=https://goerli.optimism.io
SHARED_ENV_PATH=../envs/goerli-devnet
GCMODE=full
L2GETH_IMAGE_TAG=0.5.31
DTL_IMAGE_TAG=0.5.50
HC_IMAGE_TAG=1.2.0
L2GETH_HTTP_PORT=9991
L2GETH_WS_PORT=9992
DTL_PORT=7878
GETH_INIT_SCRIPT=check-for-chaindata-berlin.sh
HEALTHCHECK__REFERENCE_RPC_PROVIDER=https://goerli.optimism.io
HEALTHCHECK__TARGET_RPC_PROVIDER=http://l2geth-replica:8545

RESTART=unless-stopped

# Sync source
ROLLUP_BACKEND=l1
DATA_TRANSPORT_LAYER__DEFAULT_BACKEND=l1
DATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND=l1
DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
DATA_TRANSPORT_LAYER__SYNC_FROM_L2=false
```

**Comment by smartcontracts** [comment]
Bedrock requires additional configuration. See here for examples of how I run my own Bedrock nodes: https://github.com/smartcontracts/simple-optimism-node
