### ISSUE TITLE
ERROR: RPC method debug_traceBlockByNumber crashed: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jacquesvcritien** [ethereum-optimism/optimism#5133]
**Describe the bug**
After updating our Goerli nodes to the latest required versions, we are seeing the following error when making debug_traceBlockByNumber RPC queries

```
ERROR[03-14|11:42:18.811] RPC method debug_traceBlockByNumber crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 1479991 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
        github.com/ethereum/go-ethereum/rpc/service.go:199 +0x89
panic({0x1706b60, 0x2785570})
        runtime/panic.go:884 +0x213
github.com/ethereum/go-ethereum/core.(*StateTransition).innerTransitionDb(0xc013d6bd80)
        github.com/ethereum/go-ethereum/core/state_transition.go:477 +0xfc6
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc013d6bd80)
        github.com/ethereum/go-ethereum/core/state_transition.go:333 +0xce
github.com/ethereum/go-ethereum/core.ApplyMessage(0x1cb2c78?, {0x1cbf5f0?, 0xc030416fa0?}, 0x0?)
        github.com/ethereum/go-ethereum/core/state_transition.go:211 +0x2a
github.com/ethereum/go-ethereum/eth/tracers.(*API).traceTx(0xc002a75db0, {0x1cb2c78, 0xc05baa3bd0}, {0x1cbf5f0, 0xc030416fa0}, 0xc0338156d0, {0x1ae73a0, 0x1ae73a8, 0xc0072834d0, 0x0, ...}, ...)
        github.com/ethereum/go-ethereum/eth/tracers/api.go:1038 +0x529
github.com/ethereum/go-ethereum/eth/tracers.(*API).traceBlock(0xc002a75db0, {0x1cb2c78?, 0xc05baa3bd0?}, 0xc030416dc0, 0xc02592bb40)
        github.com/ethereum/go-ethereum/eth/tracers/api.go:668 +0xcf2
github.com/ethereum/go-ethereum/eth/tracers.(*API).TraceBlockByNumber(0xc002a75db0, {0x1cb2c78, 0xc05baa3bd0}, 0x5?, 0xc02592bb40)
        github.com/ethereum/go-ethereum/eth/tracers/api.go:477 +0x445
reflect.Value.call({0xc00019c540?, 0xc001309dc8?, 0x7f1d469c3768?}, {0x194dab3, 0x4}, {0xc06b186c00, 0x4, 0x0?})
        reflect/value.go:586 +0xb07
reflect.Value.Call({0xc00019c540?, 0xc001309dc8?, 0x1?}, {0xc06b186c00?, 0x2?, 0x16?})
        reflect/value.go:370 +0xbc
github.com/ethereum/go-ethereum/rpc.(*callback).call(0xc0009a8a20, {0x1cb2c78?, 0xc05baa3bd0}, {0xc059487740, 0x18}, {0xc0072822a0, 0x2, 0x4d3837?})
        github.com/ethereum/go-ethereum/rpc/service.go:205 +0x3c5
github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc05686cc00?, {0x1cb2c78?, 0xc05baa3bd0?}, 0xc0470f5f10, 0x2?, {0xc0072822a0?, 0x417230?, 0x1739d80?})
        github.com/ethereum/go-ethereum/rpc/handler.go:513 +0x45
github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc0007d8d80, 0xc011a0f410, 0xc0470f5f10)
        github.com/ethereum/go-ethereum/rpc/handler.go:459 +0x239
github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc0007d8d80, 0xc007282210?, 0xc0470f5f10)
        github.com/ethereum/go-ethereum/rpc/handler.go:420 +0x237
github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0xc011a0f410)
        github.com/ethereum/go-ethereum/rpc/handler.go:256 +0x1a5
github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1()
        github.com/ethereum/go-ethereum/rpc/handler.go:348 +0xc5
created by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc
        github.com/ethereum/go-ethereum/rpc/handler.go:344 +0x8d
```

The query returns the following:

```
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"method handler crashed"}}
```

**To Reproduce**

```
curl -s -X POST -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method" :"debug_traceBlockByNumber", "params": ["0x64fe91", {"tracer": "callTracer"}],"id": 1}' http://IP:PORT
```

**Comment by protolambda** [comment]
Thank you for the bug report. This was fixed in https://github.com/ethereum-optimism/op-geth/pull/70
