### ISSUE TITLE
DTL: TypeError: Cannot read properties of null (reading 'from')

### ISSUE THREAD

**Issue by prih** [ethereum-optimism/optimism#5468]
**Describe the bug**
error occurs on block L1 16814466

```
optimism-dtl-1  | {"level":30,"time":1681733373575,"msg":"Service is starting..."}
optimism-dtl-1  | {"level":30,"time":1681733373576,"msg":"Service is initializing..."}
optimism-dtl-1  | {"level":30,"time":1681733373576,"msg":"Initializing L1 Data Transport Service..."}
optimism-dtl-1  | {"level":30,"time":1681733373736,"msg":"L2 chain ID is: 10"}
optimism-dtl-1  | {"level":30,"time":1681733373736,"msg":"BSS HF1 will activate at: 2824317"}
optimism-dtl-1  | {"level":30,"time":1681733373741,"msg":"Service is initializing..."}
optimism-dtl-1  | {"level":30,"time":1681733373746,"defaultBackend":"l1","l1GasPriceBackend":"l1","msg":"HTTP Server Options"}
optimism-dtl-1  | {"level":30,"time":1681733373746,"url":"http://192.168.0.4:8045","msg":"HTTP Server L1 RPC Provider initialized"}
optimism-dtl-1  | {"level":30,"time":1681733373746,"url":"http://192.168.0.4:8045","msg":"HTTP Server L2 RPC Provider initialized"}
optimism-dtl-1  | {"level":30,"time":1681733373746,"msg":"Service has initialized."}
optimism-dtl-1  | {"level":30,"time":1681733373746,"msg":"Service is initializing..."}
optimism-dtl-1  | {"level":30,"time":1681733373764,"addressManager":"0xdE1FCfB0851916CA5101820A69b13a4E276bd81F","msg":"Using AddressManager"}
optimism-dtl-1  | {"level":30,"time":1681733373800,"startingL1BlockNumber":13596466,"msg":"Starting sync"}
optimism-dtl-1  | {"level":30,"time":1681733373804,"msg":"Service has initialized."}
optimism-dtl-1  | {"level":30,"time":1681733373804,"msg":"Service has initialized."}
optimism-dtl-1  | {"level":30,"time":1681733373804,"msg":"Service is starting..."}
optimism-dtl-1  | {"level":30,"time":1681733373804,"msg":"Service is starting..."}
optimism-dtl-1  | {"level":30,"time":1681733373807,"host":"0.0.0.0","port":7878,"msg":"Server started and listening"}
optimism-dtl-1  | {"level":30,"time":1681733373808,"msg":"Service has started"}
optimism-dtl-1  | {"level":30,"time":1681733373812,"highestSyncedL1Block":16814466,"targetL1Block":16816466,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
optimism-dtl-1  | {"level":30,"time":1681733374286,"eventName":"TransactionEnqueued","numEvents":216,"durationMs":48,"msg":"Processed events"}
optimism-dtl-1  | {"level":50,"time":1681733418402,"extra":{"message":"TypeError: Cannot read properties of null (reading 'from')","stack":"TypeError: Cannot read properties of null (reading 'from')\n    at Object.getExtraData (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/handlers/sequencer-batch-appended.js:27:38)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async L1IngestionService._syncEvents (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:286:39)\n    at async L1IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:165:17)\n    at async L1IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async Promise.all (index 1)\n    at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:69:13)\n    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:78:9"},"msg":"Caught an unhandled error"}
optimism-dtl-1  | {"level":30,"time":1681733418904,"highestSyncedL1Block":16814466,"targetL1Block":16816466,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
optimism-dtl-1  | {"level":30,"time":1681733419270,"eventName":"TransactionEnqueued","numEvents":216,"durationMs":60,"msg":"Processed events"}
``` 

**To Reproduce**

.env
```env
# Network to run the node on ("mainnet" or "goerli")
NETWORK_NAME=mainnet

# Type of node to run ("full" or "archive"), note that "archive" is 10x bigger
NODE_TYPE=full

# Where to sync data from ("l1" or "l2"), see README
SYNC_SOURCE=l1

# Reference L2 node to run healthcheck against
HEALTHCHECK__REFERENCE_RPC_PROVIDER=https://mainnet.optimism.io

# L1 node to run fault detection against
FAULT_DETECTOR__L1_RPC_PROVIDER=http://192.168.0.4:8045

# Node to get chain data from (if SYNC_SOURCE is "l1" then use L1 node, etc.)
DATA_TRANSPORT_LAYER__RPC_ENDPOINT=http://192.168.0.4:8045
```

dtl.env
```env
DATA_TRANSPORT_LAYER__ADDRESS_MANAGER=0xdE1FCfB0851916CA5101820A69b13a4E276bd81F
DATA_TRANSPORT_LAYER__L1_START_HEIGHT=13596466
DATA_TRANSPORT_LAYER__CONFIRMATIONS=12
DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS=true
DATA_TRANSPORT_LAYER__DB_PATH=/db
DATA_TRANSPORT_LAYER__ENABLE_METRICS=true
DATA_TRANSPORT_LAYER__ETH_NETWORK_NAME=mainnet
DATA_TRANSPORT_LAYER__L2_CHAIN_ID=10
DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL=2000
DATA_TRANSPORT_LAYER__NODE_ENV=production
DATA_TRANSPORT_LAYER__POLLING_INTERVAL=500
DATA_TRANSPORT_LAYER__SENTRY_TRACE_RATE=0.05
DATA_TRANSPORT_LAYER__SERVER_HOSTNAME=0.0.0.0
DATA_TRANSPORT_LAYER__SERVER_PORT=7878
DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL=1000
```

dtl-start.sh
```bash
# Setting both endpoints doesn't hurt
export DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=$DATA_TRANSPORT_LAYER__RPC_ENDPOINT
export DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=$DATA_TRANSPORT_LAYER__RPC_ENDPOINT

# Set the backend depending on given sync source
export DATA_TRANSPORT_LAYER__DEFAULT_BACKEND=$SYNC_SOURCE
export DATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND=$SYNC_SOURCE

# Also tell the DTL to sync from the right place
if [ $SYNC_SOURCE == "l1" ]; then
  export DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
  export DATA_TRANSPORT_LAYER__SYNC_FROM_L2=false
else
  export DATA_TRANSPORT_LAYER__SYNC_FROM_L1=false
  export DATA_TRANSPORT_LAYER__SYNC_FROM_L2=true
fi

# Run the DTL
exec node \
  dist/src/services/run.js \
  $@
```

docker-compose.yml
```yaml
services:
  dtl:
    image: ethereumoptimism/data-transport-layer:${IMAGE_TAG__DTL:-latest}
    restart: unless-stopped
    entrypoint: /scripts/dtl-start.sh
    env_file:
      - ./envs/${NETWORK_NAME}/dtl.env
      - .env
    volumes:
      - /mnt/data/optimism/dtl:/db
      - ./scripts/:/scripts/
    ports:
      - ${PORT__DTL:-7878}:7878
    <<: *logging
```

**Ethereum Mainnet Node**

docker-compose.yml
```yaml
ethereum:
    image: "ethereum/client-go:v1.11.5"
    command:
      --snapshot=false
      --txlookuplimit=0
      --cache.preimages
      --rpc.allow-unprotected-txs
      --authrpc.addr 0.0.0.0
      --authrpc.vhosts *
      --cache 8192
      --http
      --http.addr 0.0.0.0
      --http.port 8045
      --http.api web3,net,eth
      --http.corsdomain *
      --http.vhosts *
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8046
      --ws.api web3,net,eth
      --ws.origins *
      --syncmode snap
      --port 30303
```

**System Specs:**
 - OS: Ubuntu 22.04.2 LTS
 - Docker 23.0.3
 - Package Version (or commit hash): ethereumoptimism/data-transport-layer:latest (9d3140b608da)

**Comment by smartcontracts** [comment]
Mmhh this is usually an issue with the L1 node

**Comment by prih** [comment]
> Mmhh this is usually an issue with the L1 node

how to check it? I tried all blocks nearby, all transactions are there... Arbitrum, Polygon - all ok with this node.

**Comment by pavelfedortsov2** [comment]
Same for me

simple-optimism-node-dtl-1  | {"level":30,"time":1682330061933,"highestSyncedL1Block":13596466,"targetL1Block":13598466,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
simple-optimism-node-dtl-1  | {"level":30,"time":1682330062022,"eventName":"TransactionEnqueued","numEvents":23,"durationMs":2,"msg":"Processed events"}
simple-optimism-node-dtl-1  | {"level":50,"time":1682330062074,"extra":{"message":"TypeError: Cannot read properties of null (reading 'from')","stack":"TypeError: Cannot read properties of null (reading 'from')\n    at Object.getExtraData (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/handlers/sequencer-batch-appended.js:27:38)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async L1IngestionService._syncEvents (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:286:39)\n    at async L1IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:165:17)\n    at async L1IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async Promise.all (index 1)\n    at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:69:13)\n    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:78:9"},"msg":"Caught an unhandled error"}
simple-optimism-node-dtl-1  | {"level":30,"time":1682330062253,"method":"GET","url":"/batch/transaction/latest","elapsed":0,"msg":"Served HTTP Request"}


geth v1.11.5
