### ISSUE TITLE
fault-detector post-bedrock crash

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#5909]
Reported by a user in discord, version 0.6.3:

```
/opt/optimism/node_modules/@ethersproject/logger/src.ts/index.ts:269
        const error: any = new Error(message);
                           ^
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="version()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (/opt/optimism/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/opt/optimism/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Interface.decodeFunctionResult (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
    at Contract.<anonymous> (/opt/optimism/node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
    at step (/opt/optimism/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/opt/optimism/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/opt/optimism/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'version()',
  data: '0x',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0xE6Dfba0953616Bacab0c9A8ecb3a9BBa77FC15c0',
  args: [],
  transaction: {
    data: '0x54fd4d50',
    to: '0xE6Dfba0953616Bacab0c9A8ecb3a9BBa77FC15c0'
  }
}
```

**Comment by annieke** [comment]
are you using the `--bedrock` flag?

**Comment by hamdiallam** [comment]
0xE6Dfba0953616Bacab0c9A8ecb3a9BBa77FC15c0 is the wrong L2OutputOracle contract defined in the SDK. OptimismPortal is also defined incorrectly

**Comment by koraykoska** [comment]
@annieke Does not help

**Comment by roninjin10** [comment]
@koraykoska can you run these commands from root of repo and report back.  

```bash
yarn clean
rm -rf node_modules packages/*/node_modules
yarn && yarn build
```

And then run the fault-detector?   The theory is that `yarn build` for the new sdk hasn't been ran since it last updated on monday.

Also you will need that --bedrock flag

**Comment by koraykoska** [comment]
The solution was to use 0.6.4. A `--bedrock` flag does not exist. Instead use this environment variable:

```
FAULT_DETECTOR__BEDROCK=true
```

**Comment by annieke** [comment]
closing this - use 0.6.4 according to [this comment](https://github.com/ethereum-optimism/optimism/issues/5909#issuecomment-1589331388); or follow [this comment](https://github.com/ethereum-optimism/optimism/issues/5909#issuecomment-1581643012) if you're building locally!

**Comment by roninjin10** [comment]
@koraykoska in the latest fault detector it defaults to bedrock true so you don't need to use the env variable or the flag
