### ISSUE TITLE
deposit ETH cannot success

### ISSUE THREAD

**Issue by 170210** [ethereum-optimism/optimism#7896]
**Describe the bug**
I've been following the [optimism-tutorial](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/cross-dom-bridge-eth) to attempt depositing/withdrawing ETH between L1 and L2. However, I encountered a failure due to eth_estimateGas as there was no "from" field in the request. 
The request body is like 
```
requestBody: '{"method":"eth_estimateGas","params":[{"value":"0xe8d4a51000","to":"0xa513e6e4b8f2a923d98304ec87f64353c4d5c853","data":"...."}],"id":46,"jsonrpc":"2.0"}'
```
Upon switching the eth-optimism/sdk from v3.0.0 to v2.0.0, I was able to achieve success.

**To Reproduce**
1. Follow the optimism-tutorial/cross-dom-bridge-eth

**Expected behavior**
```
Deposit ETH
On L1:9265774 Gwei    On L2:1000 Gwei
Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":46,\"error\":{\"code\":-32000,\"message\":\"rpc error: code = Unknown desc = insufficient balance for transfer\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"value\":\"0xe8d4a51000\",\"to\":\"0xa513e6e4b8f2a923d98304ec87f64353c4d5c853\",\"data\":\"....\"}],\"id\":46,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:8545", code=SERVER_ERROR, version=web/5.7.1)
    at Logger.makeError (/workspace/optimism-tutorial/cross-dom-bridge-eth/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/workspace/optimism-tutorial/cross-dom-bridge-eth/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at /workspace/optimism-tutorial/cross-dom-bridge-eth/node_modules/@ethersproject/web/lib/index.js:313:32
    at step (/workspace/optimism-tutorial/cross-dom-bridge-eth/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/workspace/optimism-tutorial/cross-dom-bridge-eth/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/workspace/optimism-tutorial/cross-dom-bridge-eth/node_modules/@ethersproject/web/lib/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"jsonrpc":"2.0","id":46,"error":{"code":-32000,"message":"rpc error: code = Unknown desc = insufficient balance for transfer"}}\n',
  error: Error: rpc error: code = Unknown desc = insufficient balance for transfer
      at getResult (/workspace/optimism-tutorial/cross-dom-bridge-eth/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:191:21)
      at processJsonFunc (/workspace/optimism-tutorial/cross-dom-bridge-eth/node_modules/@ethersproject/web/lib/index.js:356:22)
      at /workspace/optimism-tutorial/cross-dom-bridge-eth/node_modules/@ethersproject/web/lib/index.js:288:46
      at step (/workspace/optimism-tutorial/cross-dom-bridge-eth/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/workspace/optimism-tutorial/cross-dom-bridge-eth/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/workspace/optimism-tutorial/cross-dom-bridge-eth/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    code: -32000,
    data: undefined
  },
  requestBody: '{"method":"eth_estimateGas","params":[{"value":"0xe8d4a51000","to":"0xa513e6e4b8f2a923d98304ec87f64353c4d5c853","data":"...."}],"id":46,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'http://localhost:8545'
}
```

**Screenshots**

**System Specs:**
 - OS: Mac
 - Package Version (or commit hash): v1.1.4

**Additional context**
The same issue is https://github.com/ethereum-optimism/optimism/issues/6723

**Comment by tynes** [comment]
The sdk has been deprecated
